package com.github.laxika.magicalvibes.model.amount;

/**
 * A dynamically computed quantity attached to an effect (the numeric sibling of
 * {@link com.github.laxika.magicalvibes.model.condition.Condition}). Amounts are pure
 * data — evaluation lives in the engine's {@code AmountEvaluationService}, which
 * switches exhaustively over this sealed hierarchy so that a missing amount is a
 * compile error rather than a silent runtime fallback.
 *
 * <p>Effects that only differ in how a number is derived ("+1/+1 for each artifact you
 * control", "+X/+0 where X is the mana spent", …) should be a single effect record
 * parameterized with a {@code DynamicAmount} instead of one record per derivation.
 */
public sealed interface DynamicAmount permits
        AttachmentsOnSource,
        AttachedPermanentColorCount,
        BasicLandTypesAmongControlledLands,
        CardTypesAmongCardsInGraveyard,
        DistinctManaCostsAmongCardsInGraveyard,
        CardsDiscardedByTargetPlayerThisTurn,
        CardsDiscardedOrCycledThisTurn,
        CardsInExile,
        CardsInGraveyard,
        CardsInLibrary,
        CardsPutIntoGraveyardByTargetPlayerThisTurn,
        ColorManaSymbolsAmongControlledPermanents,
        ColorsAmongControlledPermanents,
        ColorManaSymbolsInGraveyard,
        ColorManaSymbolsInHand,
        CardsInHand,
        ChosenNumberOnSource,
        ChosenPermanentPower,
        ControllerLifeTotal,
        CountersOnLinkedPermanent,
        CountersOnGrantingPermanent,
        CountersOnSource,
        CreatureDeathsThisTurn,
        CreatureSubtypeDeathsThisTurn,
        CreaturesEnteredBattlefieldThisTurn,
        CreaturesDevoured,
        CreaturesBlockedBySource,
        CreaturesBlockingSource,
        DevouredCreaturesOfSubtype,
        DamageDealtToControllerThisTurn,
        DamageDealtToOpponentsThisTurn,
        DamageDealtToTargetPermanentThisTurn,
        DamageDealtToTargetPlayerThisTurn,
        Divided,
        DuringControllerTurn,
        EnchantedPermanentManaValue,
        EventValue,
        Fixed,
        FixedIfCondition,
        FixedIfControlMoreCreaturesThanEachOtherPlayer,
        FixedIfControlledCreaturesTotalToughnessAtLeast,
        FixedIfControlsAllNamed,
        FixedIfTargetMatches,
        FixedIfTargetPlayerControlsMoreLands,
        GreatestManaValueAmongControlled,
        GreatestPowerAmongControlled,
        GreatestToughnessAmongControlled,
        HalvedRoundedUp,
        HalfControllerLifeRoundedUp,
        HighestLifeTotalAmongPlayers,
        HighestOpponentLifeTotal,
        IfSourceAttacking,
        ImprintedCardManaValue,
        ImprintedCreaturePower,
        ImprintedCreatureToughness,
        LandsMatchingImprintedName,
        LastDiscardedCardManaValue,
        LastMilledCardColorSymbols,
        LifeGainedThisTurn,
        LifeLostThisTurn,
        ManaSpentToCast,
        MatchingCardsInHand,
        Max,
        Min,
        OpponentPoisonCounters,
        OtherAttackersSharingCreatureTypeWithTarget,
        PermanentCount,
        RepeatedAdditionalCostCount,
        Scaled,
        SourceCardPower,
        SourcePower,
        SourceToughness,
        Sum,
        TargetPlayerLifeTotal,
        TargetPlayerPoisonCounters,
        TimesSourceRegeneratedThisTurn,
        TargetManaValue,
        TargetSpellManaValue,
        TargetSpellPower,
        TargetToughness,
        TargetPower,
        TotalPowerOfCardsExiledWithSource,
        TotalToughnessOfCardsExiledWithSource,
        TotalToughnessOfControlledCreatures,
        UntappedLandsAtTurnStart,
        XValue {
}
