package com.github.laxika.magicalvibes.model.filter;

/**
 * A predicate over a {@link com.github.laxika.magicalvibes.model.Card}. Predicates are pure
 * data — evaluation lives in the engine's {@code PredicateEvaluationService}, which switches
 * exhaustively over this sealed hierarchy so that a missing predicate is a compile error
 * rather than a silent runtime fallback.
 */
public sealed interface CardPredicate permits
        CardAllOfPredicate,
        CardAnyOfPredicate,
        CardColorPredicate,
        CardHasColorManaSymbolPredicate,
        CardControllerDoesNotOwnPredicate,
        CardDoesNotShareNameWithControlledRoomPredicate,
        CardDoesNotShareLandTypeWithControlledLandPredicate,
        CardDoesNotShareColorWithSourceControlledCreaturePredicate,
        CardSharesCreatureTypeWithSourcePredicate,
        CardHasDisturbPredicate,
        CardHasCyclingPredicate,
        CardHasAdventurePredicate,
        CardHasMorphAbilityPredicate,
        CardHasEmbalmOrEternalizePredicate,
        CardHasForetellPredicate,
        CardHasFlashbackPredicate,
        CardHasKickerPredicate,
        CardHasXInManaCostPredicate,
        CardHasManaAbilityPredicate,
        CardHasNonManaActivatedAbilityPredicate,
        CardHasSourceChosenColorPredicate,
        CardHasSourceChosenCardTypePredicate,
        CardHasExactlyTwoColorsPredicate,
        CardHasExactlyNColorsPredicate,
        CardHasNoAbilitiesPredicate,
        CardHasSourceChosenSubtypePredicate,
        CardIsAuraEnchantCreaturePredicate,
        CardIsAuraPredicate,
        CardIsColorlessPredicate,
        CardIsDoubleFacedPredicate,
        CardIsHistoricPredicate,
        CardIsMulticoloredPredicate,
        CardIsPermanentPredicate,
        CardIsTokenPredicate,
        CardIsSelfPredicate,
        CardHasAwakenPredicate,
        CardKeywordPredicate,
        CardManaValueParityPredicate,
        CardNameInControllerGraveyardPredicate,
        CardManaValueAtMostPermanentCardsInControllerGraveyardPredicate,
        CardManaValueAtMostControlledLandsPredicate,
        CardManaValueAtMostSourcePowerPredicate,
        CardManaValueLessThanSourcePowerPredicate,
        CardManaValueLessThanSourceLoyaltyPredicate,
        CardMaxManaValuePredicate,
        CardMaxManaValueXPredicate,
        CardMinManaValuePredicate,
        CardNamedPredicate,
        CardNameStartsWithPredicate,
        CardNotPredicate,
        CardPowerAtLeastPredicate,
        CardPowerAtMostPredicate,
        CardPowerAtMostSourcePowerPredicate,
        CardPowerToughnessTotalAtMostPredicate,
        CardToughnessAtLeastPredicate,
        CardToughnessGreaterThanPowerPredicate,
        CardSharesCardTypeWithImprintedCardPredicate,
        CardSharesCreatureTypeWithControlledCreatureOrGraveyardPredicate,
        CardToughnessLessThanSourceToughnessPredicate,
        CardSharesNameWithAPermanentPredicate,
        CardSubtypePredicate,
        CardSupertypePredicate,
        CardTruePredicate,
        CardTypePredicate,
        PhyrexianManaPredicate {
}
