package com.github.laxika.magicalvibes.model.filter;

/**
 * A predicate over a {@link com.github.laxika.magicalvibes.model.Permanent}. Predicates are
 * pure data — evaluation lives in the engine's {@code PredicateEvaluationService}, which
 * switches exhaustively over this sealed hierarchy so that a missing predicate is a compile
 * error rather than a silent runtime fallback.
 */
public sealed interface PermanentPredicate permits
        PermanentAllOfPredicate,
        PermanentAnyOfPredicate,
        PermanentAttachedToSourceControllerPredicate,
        PermanentAttackedOrBlockedThisTurnPredicate,
        PermanentAttackedDuringControllersLastTurnPredicate,
        PermanentAttackedSourceControllerThisTurnPredicate,
        PermanentBlockedBySourcePredicate,
        PermanentCastBySourceControllerThisTurnPredicate,
        PermanentBlockingSourcePredicate,
        PermanentBlockedOrWasBlockedBySubtypeThisTurnPredicate,
        PermanentColorInPredicate,
        PermanentControlledByActivePlayerPredicate,
        PermanentControlledByDefendingPlayerPredicate,
        PermanentControlledBySourceControllerPredicate,
        PermanentControlledContinuouslySinceBeginningOfTurnPredicate,
        PermanentControllerControlsPermanentPredicate,
        PermanentDealtDamageThisTurnPredicate,
        PermanentDealtDamageToAnythingThisTurnPredicate,
        PermanentDealtDamageToSourceControllerThisTurnPredicate,
        PermanentHasAnySubtypePredicate,
        PermanentHasCountersPredicate,
        PermanentHasCumulativeUpkeepPredicate,
        PermanentHasGreatestManaValueAmongAllCreaturesPredicate,
        PermanentHasGreatestPowerAmongControlledCreaturesPredicate,
        PermanentHasKeywordPredicate,
        PermanentHasProtectionFromColorPredicate,
        PermanentHasLeastPowerAmongAllCreaturesPredicate,
        PermanentHasSameNameAsSourcePredicate,
        PermanentHasSourceChosenSubtypePredicate,
        PermanentSharesNameWithAnotherPermanentPredicate,
        PermanentSharesColorWithEquippedCreaturePredicate,
        PermanentSharesCreatureTypeWithEquippedCreaturePredicate,
        PermanentHasSubtypePredicate,
        PermanentHasSupertypePredicate,
        PermanentInCombatWithSourcePredicate,
        PermanentIsArtifactPredicate,
        PermanentIsAttackingPredicate,
        PermanentIsAttackingSourceControllerPredicate,
        PermanentIsAuraAttachedToCreaturePredicate,
        PermanentIsAuraAttachedToSourcePredicate,
        PermanentIsBattlePredicate,
        PermanentIsBlockedPredicate,
        PermanentIsBlockingPredicate,
        PermanentIsCreaturePredicate,
        PermanentIsEnchantedPredicate,
        PermanentIsEnchantmentPredicate,
        PermanentIsHistoricPredicate,
        PermanentIsHostOfSourceAuraPredicate,
        PermanentIsLandPredicate,
        PermanentIsUnblockedAttackingPredicate,
        PermanentIsMonocoloredPredicate,
        PermanentIsMulticoloredPredicate,
        PermanentIsPlaneswalkerPredicate,
        PermanentIsSourceCardPredicate,
        PermanentIsSpecificPermanentPredicate,
        PermanentIsTappedPredicate,
        PermanentIsTokenPredicate,
        PermanentManaValueAtMostOwnCountersPredicate,
        PermanentManaValueEqualsXPredicate,
        PermanentMaxManaValuePredicate,
        PermanentMinManaValuePredicate,
        PermanentNamedPredicate,
        PermanentNameInPredicate,
        PermanentNotPredicate,
        PermanentOwnedBySourceControllerPredicate,
        PermanentPowerAtLeastPredicate,
        PermanentPowerAtMostControlledCreatureCountPredicate,
        PermanentPowerAtMostPredicate,
        PermanentPowerAtMostSourceCountersPredicate,
        PermanentPowerAtMostSourcePowerPredicate,
        PermanentPowerAtMostXPredicate,
        PermanentPowerLessThanSourcePowerPredicate,
        PermanentToughnessAtLeastPredicate,
        PermanentToughnessAtMostPredicate,
        PermanentToughnessLessThanSourcePowerPredicate,
        PermanentTruePredicate {
}
