package com.github.laxika.magicalvibes.model.filter;

/**
 * A predicate over a {@link com.github.laxika.magicalvibes.model.StackEntry}. Predicates are
 * pure data — evaluation lives in the engine (the {@code PredicateEvaluationService} for
 * static-effect contexts and {@code TargetLegalityService} for targeting contexts), each of
 * which dispatches over this sealed hierarchy.
 */
public sealed interface StackEntryPredicate permits
        StackEntryAllOfPredicate,
        StackEntryAnyOfPredicate,
        StackEntryCardIdPredicate,
        StackEntryCardTypeInPredicate,
        StackEntryCastFromZonePredicate,
        StackEntryCastWithAdventurePredicate,
        StackEntryCastWithWarpCostPredicate,
        StackEntryColorInPredicate,
        StackEntryIsMulticoloredPredicate,
        StackEntryControlledByChosenPlayerPredicate,
        StackEntryControlledByEnchantedPlayerPredicate,
        StackEntryControlledByPredicate,
        StackEntryHasAnyTargetPredicate,
        StackEntryHasSourceChosenSubtypePredicate,
        StackEntryHasTargetPredicate,
        StackEntryHasXInManaCostPredicate,
        StackEntryIsNthSpellCastThisTurnPredicate,
        StackEntryKickedPredicate,
        StackEntryIsSingleTargetPredicate,
        StackEntryManaValuePredicate,
        StackEntryMaxManaValuePredicate,
        StackEntryManaSpentLessThanManaValuePredicate,
        StackEntryManaValueEqualsXPredicate,
        StackEntryManaValueEqualsSourceCountersPredicate,
        StackEntryManaValueEqualsSourceChosenNumberPredicate,
        StackEntryManaValueGreaterThanControllerExperienceCountersPredicate,
        StackEntryManaValueEqualsSourcePowerPredicate,
        StackEntryManaValueAtMostSourcePowerPredicate,
        StackEntryManaValuePowerOrToughnessEqualsPredicate,
        StackEntryManaValuePowerOrToughnessEqualsSourceChosenNumberPredicate,
        StackEntryPowerOrToughnessAtMostPredicate,
        StackEntryManaValueParityMatchesSourceChosenParityPredicate,
        StackEntryManaValueAtMostControlledCountPredicate,
        StackEntryManaValueAtMostControllerGraveyardCountPredicate,
        StackEntrySharesColorOrManaValueWithImprintedCardPredicate,
        StackEntryNotPredicate,
        StackEntryIsCopyPredicate,
        StackEntryNotTargetedByNamedCreatureAbilityPredicate,
        StackEntrySharesChosenNameWithSourcePredicate,
        StackEntryIsCardExiledWithSourcePredicate,
        StackEntrySharesNameWithCardExiledWithSourcePredicate,
        StackEntrySourceIsColorlessPredicate,
        StackEntrySourceHasSupertypePredicate,
        StackEntrySourceIsCommanderPredicate,
        StackEntrySupertypeInPredicate,
        StackEntryTargetsAnyPlayerPredicate,
        StackEntryTargetsOnlySinglePermanentOrPlayerPredicate,
        StackEntryTargetsOnlySingleCreaturePredicate,
        StackEntryTargetsPermanentPredicate,
        StackEntryTargetsSourcePredicate,
        StackEntryTargetsYouOrCreatureYouControlPredicate,
        StackEntryTargetsYouPredicate,
        StackEntryTargetsYourPermanentPredicate,
        StackEntrySubtypeInPredicate,
        StackEntryTruePredicate,
        StackEntryTypeInPredicate {
}
