package com.github.laxika.magicalvibes.model.condition;

/**
 * A game-state condition attached to a conditional effect wrapper. Conditions are pure
 * data — evaluation lives in the engine's {@code ConditionEvaluationService}, which
 * switches exhaustively over this sealed hierarchy so that a missing condition is a
 * compile error rather than a silent runtime fallback.
 */
public sealed interface Condition permits
        ActivePlayerControlsMoreLandsThanEachOtherPlayer,
        ActivePlayerControlsPermanent,
        ActivePlayerHandAtLeast,
        ActivePlayerHandAtMost,
        ActivePlayerHandEmpty,
        ActivationCount,
        AllConditions,
        AllMatchingCreaturesAttack,
        AllOf,
        AnotherPermanentEnteredLastTurn,
        AnotherPermanentEnteredThisTurn,
        AnOpponentHandEmpty,
        AnOpponentHasMoreCardsInHandThanController,
        AnOpponentHasMoreLifeThanController,
        AnOpponentLifeAtMost,
        AnyGraveyardAtLeast,
        AnyLibraryAtMost,
        AnyPlayerLostLifeThisTurn,
        AnyPlayerControlsPermanent,
        AnyPlayerControlsPermanentCount,
        AnyPlayerControlsPermanentCountAtMost,
        AnyOf,
        AttachedPermanentControllerControlsNoOther,
        AttackedWithCreaturesThisTurn,
        AttackedWithCreaturesOfSubtypeThisTurn,
        AttacksAlone,
        BlockedByMinCreatures,
        BuybackPaid,
        CameUnderControlThisTurn,
        CardDirectlyAboveSelfInGraveyard,
        CardsAboveSelfInGraveyard,
        CardsInLibraryAtLeast,
        CardsInHandAtLeast,
        CardsInHandAtMost,
        CardsLeftGraveyardThisTurn,
        CastForProwlCost,
        CastFromZone,
        CastNotFromHand,
        WasCast,
        ChosenColorStrictlyMostCommonAmongOpponentNontokens,
        ColorMostCommonAmongAllPermanents,
        ColorSpentToCast,
        ControllerCastAnotherSpellThisTurn,
        ControllerCastSpellThisTurn,
        ControllerCreatureSpellCounteredByOpponentThisTurn,
        ControllerDealtDamageThisTurn,
        ControllerHadNoCardsInHandAtTurnStart,
        ControllerDealtDamageByAtLeastCreaturesThisTurn,
        ControllerDrewAtLeastCardsThisTurn,
        ControllerHasMoreLifeThanAnOpponent,
        ControllerControlsMoreLandsThanOpponent,
        ControllerControlsMorePermanentsThanEachOtherPlayer,
        ControllerHandEmpty,
        ControllerLifeAtLeast,
        ControllerLifeAtMost,
        ControllerMainPhase,
        EachPlayerLifeAtMost,
        ControllerDidntLoseLifeThisTurn,
        ControllerEnergyAtLeast,
        ControllerLostLifeLastTurn,
        ControllerOwnTurnCountAtMost,
        ControllerTurn,
        ControlsAnotherPermanent,
        ControlsDistinctPermanentNamesCount,
        ControlsMoreCreaturesThanOpponent,
        APlayerControlsMoreCreaturesThanEachOtherPlayer,
        ControlsOtherPermanentCount,
        ControlsOtherThanTriggeringPermanentCount,
        ControlsPermanent,
        ControlsPermanentCount,
        ControlsPermanentCountAtMost,
        ControlsPermanentsWithDifferentNames,
        ControlledCreaturesTotalPowerAtLeast,
        ControlsCreatureWithGreatestPower,
        ControlsEachCreatureWithGreatestPower,
        Coven,
        CreatureAttackingController,
        CreatureDiedUnderYourControlThisTurn,
        DealtDamageByRedSpellThisTurn,
        DefendingPlayerControlsPermanent,
        DefendingPlayerPoisoned,
        Delirium,
        DevotionToColorAtLeast,
        DevotionToColorsAtLeast,
        DevouredCreature,
        DidntActivateLoyaltyAbilityThisTurn,
        DidntAttack,
        DidntGainLifeThisTurn,
        DuringCombat,
        Enchanted,
        EnchantedByAtLeastAuras,
        EnchantedCreatureDidntAttack,
        EnchantedCreaturePowerAtLeast,
        EnchantedPermanentMatches,
        FirstCombatPhase,
        EndStepPlayerDidntCastCreatureSpell,
        ExtraTurn,
        Equipped,
        GainedLifeThisTurn,
        GraveyardCardThreshold,
        HasAttacker,
        ImprintedCardMatches,
        ImprintedCardNameMatchesEnteringPermanent,
        Kicked,
        Metalcraft,
        MinimumAttackers,
        Morbid,
        NoCardsExiledWithSource,
        NoOtherPermanent,
        SourceRegeneratedThisTurn,
        NoPlayerHasCardsInHand,
        NoSpellsCastLastTurn,
        NotCondition,
        NotControllerTurn,
        NotKicked,
        Overloaded,
        NthAbilityResolutionThisTurn,
        OpponentControlsMoreCreatures,
        OpponentControlsMoreLands,
        OpponentCastSpellThisTurn,
        OpponentCastThreeOrMoreSpellsThisTurn,
        OpponentControlsPermanent,
        OpponentControlsPermanentCount,
        OpponentDealtDamageThisTurn,
        OpponentDrewAtLeastCardsThisTurn,
        OpponentGraveyardAtLeast,
        OpponentPutThreeOrMoreCardsIntoGraveyardThisTurn,
        OpponentGainedLifeThisTurn,
        OpponentLostLifeLastTurn,
        OpponentLostLifeThisTurn,
        OpponentOwnsCardInExile,
        OpponentPermanentEnteredThisTurn,
        NoncreaturePermanentDestroyedByOpponentThisTurn,
        OpponentPoisoned,
        OpponentSearchedLibraryThisTurn,
        PermanentEnteredThisTurn,
        PlusOnePlusOneCounterPutOnControlledPermanentThisTurn,
        PutCounterOnCreatureThisTurn,
        PutCounterCostPaid,
        Raid,
        SelfDealtDamageThisTurn,
        SelfDealtDamageToOpponentThisTurn,
        SourceHasDealtDamage,
        SelfHasKeyword,
        SelfWasDealtDamageThisTurn,
        SourceAddedManaThisTurn,
        SourceCardInCommandZone,
        SourceCardInGraveyard,
        SourceCanSoulbond,
        SourceAttackedOrBlockedThisTurn,
        SourceCounterThreshold,
        SourceDamagedCreatureDiedThisTurn,
        SourceEnteredThisTurn,
        SourceEnteredBattlefieldThisTurn,
        SourceHasSubtype,
        SourceBlockedOrWasBlockedByColorThisTurn,
        SourceIsAttacking,
        SourceIsAttackingOrBlocking,
        SourceIsCreature,
        SourceIsEnchantment,
        SourceIsOnBattlefield,
        SourceWasBlockedThisTurn,
        SourceIsPaired,
        SourceIsMonstrous,
        SourceIsRenowned,
        SourceIsTapped,
        SourceIsToken,
        SourceUntapped,
        SpellManaSpentAtLeast,
        SpellXAtLeast,
        TargetPermanentManaValueEqualsControllerUnspentMana,
        TargetPermanentMatches,
        TargetToughnessAtMostControllerGraveyardCount,
        TargetPlayerLifeTotalEquals,
        TargetPlayerHasMoreCardsInHandThanController,
        TargetPlayerHandEmpty,
        TargetSpellCanBeCountered,
        TargetSpellMatches,
        TopCardOfLibraryColor,
        TopCardOfLibraryType,
        TotalPermanentCountEven,
        TwoOrMoreSpellsCastLastTurn,
        WonClash {

    /** Human-readable condition name for log messages (e.g. "metalcraft", "equipped"). */
    String conditionName();

    /** Human-readable reason shown when the condition is not met (e.g. "fewer than three artifacts"). */
    String conditionNotMetReason();

    /**
     * True when, used as an ETB intervening-"if" (CR 603.4), this condition is checked against
     * game state as the trigger would go on the stack (e.g. Metalcraft, Morbid, Raid) rather
     * than being a casting choice already known at cast time (e.g. Kicked). A gate-conditional
     * ETB never creates a cast-time target requirement — its target is chosen only when the
     * trigger is put on the stack (CR 603.3d), and only if the gate is met at that point.
     */
    default boolean isEtbTriggerGate() {
        return false;
    }
}
