package com.github.laxika.magicalvibes.cards.m;

import com.github.laxika.magicalvibes.model.Card;
import com.github.laxika.magicalvibes.model.EffectSlot;
import com.github.laxika.magicalvibes.model.ManaColor;
import com.github.laxika.magicalvibes.model.effect.AwardManaEffect;
import com.github.laxika.magicalvibes.cards.CardRegistration;

@CardRegistration(set = "10E", collectorNumber = "376")
@CardRegistration(set = "10E", collectorNumber = "377")
@CardRegistration(set = "10E", collectorNumber = "378")
@CardRegistration(set = "10E", collectorNumber = "379")
@CardRegistration(set = "M10", collectorNumber = "242")
@CardRegistration(set = "M10", collectorNumber = "243")
@CardRegistration(set = "M10", collectorNumber = "244")
@CardRegistration(set = "M10", collectorNumber = "245")
@CardRegistration(set = "SOM", collectorNumber = "242")
@CardRegistration(set = "SOM", collectorNumber = "243")
@CardRegistration(set = "SOM", collectorNumber = "244")
@CardRegistration(set = "SOM", collectorNumber = "245")
@CardRegistration(set = "MBS", collectorNumber = "152")
@CardRegistration(set = "MBS", collectorNumber = "153")
@CardRegistration(set = "NPH", collectorNumber = "172")
@CardRegistration(set = "NPH", collectorNumber = "173")
@CardRegistration(set = "M11", collectorNumber = "242")
@CardRegistration(set = "M11", collectorNumber = "243")
@CardRegistration(set = "M11", collectorNumber = "244")
@CardRegistration(set = "M11", collectorNumber = "245")
@CardRegistration(set = "ISD", collectorNumber = "259")
@CardRegistration(set = "ISD", collectorNumber = "260")
@CardRegistration(set = "ISD", collectorNumber = "261")
@CardRegistration(set = "DOM", collectorNumber = "262")
@CardRegistration(set = "DOM", collectorNumber = "263")
@CardRegistration(set = "DOM", collectorNumber = "264")
@CardRegistration(set = "DOM", collectorNumber = "265")
@CardRegistration(set = "XLN", collectorNumber = "272")
@CardRegistration(set = "XLN", collectorNumber = "273")
@CardRegistration(set = "XLN", collectorNumber = "274")
@CardRegistration(set = "XLN", collectorNumber = "275")
@CardRegistration(set = "SOS", collectorNumber = "270")
@CardRegistration(set = "SOS", collectorNumber = "278")
@CardRegistration(set = "SOS", collectorNumber = "279")
@CardRegistration(set = "8ED", collectorNumber = "343")
@CardRegistration(set = "8ED", collectorNumber = "344")
@CardRegistration(set = "8ED", collectorNumber = "345")
@CardRegistration(set = "8ED", collectorNumber = "346")
@CardRegistration(set = "9ED", collectorNumber = "343")
@CardRegistration(set = "9ED", collectorNumber = "344")
@CardRegistration(set = "9ED", collectorNumber = "345")
@CardRegistration(set = "9ED", collectorNumber = "346")
@CardRegistration(set = "POR", collectorNumber = "208")
@CardRegistration(set = "POR", collectorNumber = "209")
@CardRegistration(set = "POR", collectorNumber = "210")
@CardRegistration(set = "POR", collectorNumber = "211")
@CardRegistration(set = "LRW", collectorNumber = "294")
@CardRegistration(set = "LRW", collectorNumber = "295")
@CardRegistration(set = "LRW", collectorNumber = "296")
@CardRegistration(set = "LRW", collectorNumber = "297")
@CardRegistration(set = "P02", collectorNumber = "160")
@CardRegistration(set = "P02", collectorNumber = "161")
@CardRegistration(set = "P02", collectorNumber = "162")
@CardRegistration(set = "PTK", collectorNumber = "175")
@CardRegistration(set = "PTK", collectorNumber = "176")
@CardRegistration(set = "PTK", collectorNumber = "177")
@CardRegistration(set = "SHM", collectorNumber = "294")
@CardRegistration(set = "SHM", collectorNumber = "295")
@CardRegistration(set = "SHM", collectorNumber = "296")
@CardRegistration(set = "SHM", collectorNumber = "297")
@CardRegistration(set = "7ED", collectorNumber = "337")
@CardRegistration(set = "7ED", collectorNumber = "338")
@CardRegistration(set = "7ED", collectorNumber = "339")
@CardRegistration(set = "7ED", collectorNumber = "340")
@CardRegistration(set = "6ED", collectorNumber = "343")
@CardRegistration(set = "6ED", collectorNumber = "344")
@CardRegistration(set = "6ED", collectorNumber = "345")
@CardRegistration(set = "6ED", collectorNumber = "346")
@CardRegistration(set = "ALA", collectorNumber = "242")
@CardRegistration(set = "ALA", collectorNumber = "243")
@CardRegistration(set = "ALA", collectorNumber = "244")
@CardRegistration(set = "ALA", collectorNumber = "245")
@CardRegistration(set = "5ED", collectorNumber = "442")
@CardRegistration(set = "5ED", collectorNumber = "443")
@CardRegistration(set = "5ED", collectorNumber = "444")
@CardRegistration(set = "5ED", collectorNumber = "445")
@CardRegistration(set = "4ED", collectorNumber = "373")
@CardRegistration(set = "4ED", collectorNumber = "374")
@CardRegistration(set = "4ED", collectorNumber = "375")
@CardRegistration(set = "AKH", collectorNumber = "253")
@CardRegistration(set = "AKH", collectorNumber = "264")
@CardRegistration(set = "AKH", collectorNumber = "265")
@CardRegistration(set = "AKH", collectorNumber = "266")
public class Mountain extends Card {

    public Mountain() {
        addEffect(EffectSlot.ON_TAP, new AwardManaEffect(ManaColor.RED));
    }
}
