package com.github.laxika.magicalvibes.service.effect.normalfx;

import com.github.laxika.magicalvibes.networking.SessionManager;
import com.github.laxika.magicalvibes.networking.service.CardViewFactory;
import com.github.laxika.magicalvibes.service.DrawService;
import com.github.laxika.magicalvibes.service.GameBroadcastService;
import com.github.laxika.magicalvibes.service.GameOutcomeService;
import com.github.laxika.magicalvibes.service.WarpWorldService;
import com.github.laxika.magicalvibes.service.battlefield.BattlefieldEntryService;
import com.github.laxika.magicalvibes.service.battlefield.CreatureControlService;
import com.github.laxika.magicalvibes.service.battlefield.GameQueryService;
import com.github.laxika.magicalvibes.service.battlefield.LegendRuleService;
import com.github.laxika.magicalvibes.service.battlefield.PermanentRemovalService;
import com.github.laxika.magicalvibes.service.effect.EffectHandlerRegistry;
import com.github.laxika.magicalvibes.service.exile.ExileService;
import com.github.laxika.magicalvibes.service.graveyard.GraveyardService;
import com.github.laxika.magicalvibes.service.input.PlayerInputService;
import com.github.laxika.magicalvibes.service.trigger.TriggerCollectionService;

import java.util.List;

/**
 * Single source of truth for instantiating the migrated {@link NormalEffectHandlerBean} handlers in
 * non-Spring sites (e.g. {@code GameTestHarness}, {@code GameSimulator}).
 *
 * <p>In Spring, these handlers are discovered as {@code @Component}s; outside Spring, callers use
 * {@link #createAll} to build the same set manually and {@link #registerAll} to register them. As
 * more domains migrate, only this factory needs updating â€” non-Spring sites never change again.
 *
 * <p>Currently holds the <b>Life</b>, <b>Boost</b>, <b>Damage</b>, <b>Destruction</b>,
 * <b>Permanent Control</b>, <b>Permanent Counter</b>, <b>Player Interaction</b>,
 * <b>Tap/Untap</b>, <b>Keyword Grant</b>, <b>Animation</b>, <b>Card-specific</b>, and <b>Graveyard Return</b> domain handlers.
 */
public final class NormalEffectHandlerBeanFactory {

    private NormalEffectHandlerBeanFactory() {
    }

    public static List<NormalEffectHandlerBean> createAll(LifeSupport lifeSupport,
                                                          TapUntapSupport tapUntapSupport,
                                                          AnimationSupport animationSupport,
                                                          DamageSupport damageSupport,
                                                          DestructionSupport destructionSupport,
                                                          GraveyardReturnSupport graveyardReturnSupport,
                                                          PermanentControlSupport permanentControlSupport,
                                                          PermanentCounterSupport permanentCounterSupport,
                                                          BattlefieldEntryService battlefieldEntryService,
                                                          LegendRuleService legendRuleService,
                                                          CreatureControlService creatureControlService,
                                                          GameQueryService gameQueryService,
                                                          GameBroadcastService gameBroadcastService,
                                                          GameOutcomeService gameOutcomeService,
                                                          GraveyardService graveyardService,
                                                          ExileService exileService,
                                                          PermanentRemovalService permanentRemovalService,
                                                          TriggerCollectionService triggerCollectionService,
                                                          PlayerInputService playerInputService,
                                                          DrawService drawService,
                                                          SessionManager sessionManager,
                                                          CardViewFactory cardViewFactory,
                                                          CardSpecificSupport cardSpecificSupport,
                                                          WarpWorldService warpWorldService,
                                                          EffectHandlerRegistry effectHandlerRegistry) {
        PlayerInteractionSupport playerInteractionSupport = new PlayerInteractionSupport(
                drawService, graveyardService, gameQueryService, gameBroadcastService, playerInputService,
                sessionManager, cardViewFactory, permanentRemovalService, battlefieldEntryService,
                triggerCollectionService);
        CreateTokenCopyOfImprintedCardEffectHandler createTokenCopyOfImprintedCardEffectHandler =
                new CreateTokenCopyOfImprintedCardEffectHandler(
                        battlefieldEntryService, gameQueryService, gameBroadcastService);
        PutCounterOnTargetPermanentEffectHandler putCounterOnTargetPermanentEffectHandler =
                new PutCounterOnTargetPermanentEffectHandler(gameQueryService, permanentCounterSupport);
        return List.of(
                new GainLifeEffectHandler(lifeSupport),
                new PayXManaGainXLifeEffectHandler(lifeSupport, gameBroadcastService, playerInputService),
                new GainLifePerCardsInHandEffectHandler(lifeSupport, gameBroadcastService),
                new GainLifePerCreatureOnBattlefieldEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new GainLifePerMatchingPermanentOnBattlefieldEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new GainLifePerControlledMatchingPermanentEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new GainLifeForEachSubtypeOnBattlefieldEffectHandler(lifeSupport),
                new GainLifePerControlledCreatureEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new GainLifePerGraveyardCardEffectHandler(lifeSupport, gameBroadcastService),
                new GainLifePerCreatureCardInGraveyardEffectHandler(lifeSupport, gameBroadcastService),
                new GainLifeEqualToTargetToughnessEffectHandler(lifeSupport, gameQueryService),
                new GainLifeEqualToXValueEffectHandler(lifeSupport),
                new GainLifeMultipliedByXValueEffectHandler(lifeSupport),
                new GainLifeEqualToGreatestPowerAmongOwnCreaturesEffectHandler(lifeSupport, gameQueryService),
                new GainLifeEqualToChargeCountersOnSourceEffectHandler(lifeSupport, gameBroadcastService),
                new DoubleTargetPlayerLifeEffectHandler(lifeSupport, gameBroadcastService),
                new SetTargetPlayerLifeToHalfStartingEffectHandler(lifeSupport, gameBroadcastService),
                new SetTargetPlayerLifeToSpecificValueEffectHandler(lifeSupport, gameBroadcastService),
                new ExchangeTargetPlayersLifeTotalsEffectHandler(gameQueryService, gameBroadcastService, triggerCollectionService),
                new ExchangeLifeTotalWithCreatureStatEffectHandler(gameQueryService, gameBroadcastService, triggerCollectionService),
                new EnchantedCreatureControllerLosesLifeEffectHandler(gameQueryService, gameBroadcastService),
                new LoseLifeEffectHandler(lifeSupport),
                new TargetSpellControllerLosesLifeEffectHandler(lifeSupport),
                new EachOpponentLosesLifeEffectHandler(lifeSupport),
                new EachOpponentLosesLifeAndControllerGainsLifeLostEffectHandler(lifeSupport),
                new EachOpponentLosesXLifeAndControllerGainsLifeLostEffectHandler(lifeSupport),
                new EachPlayerLosesLifeEffectHandler(lifeSupport),
                new EachPlayerLosesFractionOfLifeRoundedUpEffectHandler(lifeSupport),
                new EachPlayerLosesLifePerCreatureControlledEffectHandler(lifeSupport),
                new TargetPlayerLosesLifeAndControllerGainsLifeEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new DrainLifePerControlledPermanentEffectHandler(lifeSupport, gameQueryService, gameBroadcastService),
                new TargetPlayerLosesLifePerControlledPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new TargetPlayerLosesLifeEffectHandler(gameQueryService, gameBroadcastService),
                new TargetPlayerGainsLifeEffectHandler(lifeSupport),
                new EachTargetPlayerGainsLifeEffectHandler(lifeSupport),
                new GiveEnchantedPermanentControllerPoisonCountersEffectHandler(gameQueryService, gameBroadcastService),
                new DamageSourceControllerGetsPoisonCounterEffectHandler(gameQueryService, gameBroadcastService),
                new GiveControllerPoisonCountersEffectHandler(lifeSupport),
                new GiveEachPlayerPoisonCountersEffectHandler(lifeSupport),
                new GiveTargetPlayerPoisonCountersEffectHandler(lifeSupport),
                new GiveControllerPoisonCountersOnTargetDeathThisTurnEffectHandler(gameQueryService),
                new AwardRestrictedManaEffectHandler(gameBroadcastService),
                new AwardManaEffectHandler(gameBroadcastService),
                new AddManaPerControlledPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new BoostSelfEffectHandler(gameQueryService, gameBroadcastService),
                new DoubleSelfPowerToughnessEffectHandler(gameQueryService, gameBroadcastService),
                new BoostSelfPerBlockingCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new BoostSelfPerOtherAttackingSubtypeEffectHandler(gameQueryService, gameBroadcastService),
                new BoostSelfPerControlledPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new BoostTargetCreaturePerControlledPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new BoostTargetCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new BoostTargetCreatureXEffectHandler(gameQueryService, gameBroadcastService),
                new SwitchPowerToughnessEffectHandler(gameQueryService, gameBroadcastService),
                new BoostFirstTargetCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new BoostSecondTargetCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new BoostAllOwnCreaturesEffectHandler(gameQueryService, gameBroadcastService),
                new BoostAllOwnCreaturesByGreatestPowerEffectHandler(gameQueryService, gameBroadcastService),
                new BoostAllCreaturesEffectHandler(gameQueryService, gameBroadcastService),
                new BoostAllCreaturesXEffectHandler(gameQueryService, gameBroadcastService),
                new TapSubtypeBoostSelfAndDamageDefenderEffectHandler(gameQueryService, gameBroadcastService, playerInputService),
                new SetBasePowerToughnessUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new BoostAllOwnCreaturesByCreatureCardsInGraveyardEffectHandler(gameQueryService, gameBroadcastService),
                new DealXDamageToTargetCreatureEffectHandler(damageSupport, gameQueryService),
                new DealDamageToTargetCreatureEffectHandler(damageSupport, gameQueryService),
                new DealDamageToBlockedAttackersOnDeathEffectHandler(damageSupport, gameQueryService),
                new DealDamageToTargetCreatureEqualToControlledSubtypeCountEffectHandler(damageSupport, gameQueryService, lifeSupport),
                new DealDamageToAnyTargetEqualToControlledSubtypeCountAndGainLifeEffectHandler(damageSupport, gameQueryService, gameOutcomeService, lifeSupport),
                new DealXDamageDividedAmongTargetAttackingCreaturesEffectHandler(damageSupport, gameQueryService),
                new MassDamageEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToEachPlayerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToEachOpponentEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToEachCreatureAndPlaneswalkerOpponentsControlEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealXDamageToAnyTargetEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealXDamageDividedEvenlyAmongTargetsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealXDamageToEachTargetEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealXDamageToAnyTargetAndGainXLifeEffectHandler(damageSupport, gameQueryService, gameOutcomeService, lifeSupport),
                new DealDamageToTargetPlayerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToSecondaryTargetEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToTriggeringPermanentControllerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToTargetPlayerByHandSizeEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToTargetPlayerEqualToCardTypeCountInGraveyardEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageIfFewCardsInHandEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToAnyTargetEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToAttackedTargetEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToTargetOpponentOrPlaneswalkerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToTargetOpponentAndUpToCreaturesThatPlayerControlsEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new MillControllerAndDealDamageByHighestManaValueEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService, graveyardService),
                new DealDividedDamageToAnyTargetsEffectHandler(damageSupport),
                new DealDividedDamageAmongTargetCreaturesEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealXDamageDividedAmongTargetCreaturesCantBlockEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDividedDamageAmongAnyTargetsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToTargetAndTheirCreaturesEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToEachCreatureDamagedPlayerControlsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToTargetCreatureOrPlaneswalkerEffectHandler(damageSupport, gameQueryService),
                new DealDamageToAllCreaturesAndPlaneswalkersTargetControlsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToAllCreaturesTargetControlsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToAnyTargetEqualToChargeCountersOnSourceEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageEqualToSourcePowerToAnyTargetEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageEqualToSourceToughnessToTargetCreatureEffectHandler(damageSupport, gameQueryService),
                new SourceFightsTargetCreatureEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new PlaneswalkerDealDamageAndReceivePowerDamageEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new PackHuntEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealOrderedDamageToAnyTargetsEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToAnyTargetAndGainLifeEffectHandler(damageSupport, gameQueryService, gameOutcomeService, lifeSupport),
                new FirstTargetDealsPowerDamageToSecondTargetEffectHandler(damageSupport, gameQueryService, gameBroadcastService),
                new FirstTargetFightsSecondTargetEffectHandler(damageSupport, gameQueryService, gameBroadcastService),
                new MassFightTargetCreatureEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new RevealTopCardDealManaValueDamageEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToControllerEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new ExileUntilNonlandToHandRepeatIfHighMVEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToEnchantedPlayerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new EnchantedCreatureDealsDamageToItsOwnerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new EnchantedCreatureDealsDamageEqualToDealtDamageToControllerEffectHandler(damageSupport, gameQueryService, gameOutcomeService),
                new DealDamageToTargetControllerIfTargetHasKeywordEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToTargetCreatureControllerEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToEachOpponentEqualToCardsDrawnThisTurnEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new DealDamageToEachOpponentEqualToPlusOnePlusOneCountersOnSourceEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService),
                new SacrificeSelfAndDealDamageToDamagedPlayerEffectHandler(damageSupport, gameQueryService, gameBroadcastService, gameOutcomeService, permanentRemovalService),
                new BoostColorSourceDamageThisTurnEffectHandler(gameBroadcastService),
                new DestroyAllPermanentsEffectHandler(destructionSupport, gameQueryService),
                new DestroyAllPermanentsAndGainLifePerDestroyedEffectHandler(destructionSupport, gameBroadcastService, gameQueryService, graveyardService, lifeSupport, permanentRemovalService),
                new EachPlayerChoosesCreatureDestroyRestEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new DestroyAllCreaturesAndCreateTokenFromDestroyedCountEffectHandler(destructionSupport, battlefieldEntryService, gameBroadcastService, gameQueryService, graveyardService, permanentRemovalService),
                new DestroyNonlandPermanentsWithManaValueEqualToChargeCountersEffectHandler(destructionSupport),
                new DestroyNonlandPermanentsWithManaValueXDealtCombatDamageEffectHandler(destructionSupport, gameBroadcastService),
                new DestroyTargetPermanentEffectHandler(destructionSupport, gameQueryService),
                new DestroyOneOfTargetsAtRandomEffectHandler(destructionSupport, gameQueryService),
                new DestroyRandomOpponentPermanentWithCounterEffectHandler(destructionSupport),
                new DestroyEquipmentAttachedToTargetCreatureEffectHandler(destructionSupport),
                new DestroyEquipmentOnEquippedCombatOpponentAtEndOfCombatEffectHandler(destructionSupport, gameQueryService),
                new DestroyTargetAndControllerLosesLifePerCreatureDeathsEffectHandler(destructionSupport, gameBroadcastService, gameOutcomeService, gameQueryService),
                new DestroyTargetLandAndDamageControllerEffectHandler(destructionSupport, gameBroadcastService, gameOutcomeService, gameQueryService),
                new DestroyTargetPermanentAndDamageControllerIfDestroyedEffectHandler(destructionSupport, gameOutcomeService, gameQueryService),
                new DestroyTargetPermanentAndGiveControllerPoisonCountersEffectHandler(destructionSupport, gameBroadcastService, gameOutcomeService, gameQueryService),
                new DestroyTargetPermanentAndControllerLosesLifeEffectHandler(destructionSupport, gameBroadcastService, gameOutcomeService, gameQueryService),
                new SacrificeCreatureEffectHandler(destructionSupport),
                new SacrificeCreatureAndControllerGainsLifeEqualToToughnessEffectHandler(destructionSupport, gameBroadcastService, gameQueryService, lifeSupport, playerInputService),
                new ControllerSacrificesCreatureEffectHandler(destructionSupport),
                new SacrificeAttackingCreaturesEffectHandler(destructionSupport, gameBroadcastService, gameQueryService, playerInputService),
                new EachOpponentSacrificesCreatureEffectHandler(destructionSupport),
                new EachPlayerSacrificesPermanentsEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new EachOpponentSacrificesPermanentsEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new TargetPlayerSacrificesPermanentsEffectHandler(destructionSupport, gameBroadcastService, gameQueryService, playerInputService),
                new DamageSourceControllerSacrificesPermanentsEffectHandler(destructionSupport, gameBroadcastService, playerInputService),
                new SacrificeOtherCreatureOrDamageEffectHandler(destructionSupport, gameOutcomeService, gameQueryService, playerInputService),
                new SacrificeOtherCreatureOpponentsLoseLifeOrTapAndLoseLifeEffectHandler(destructionSupport, gameBroadcastService, gameOutcomeService, gameQueryService, lifeSupport, playerInputService),
                new ForcedCostOrElseEffectHandler(destructionSupport, gameQueryService, playerInputService),
                new DestroyCreatureBlockingThisEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new DestroyBlockedCreatureAndSelfEffectHandler(destructionSupport, gameQueryService),
                new DestroySourcePermanentEffectHandler(destructionSupport, gameQueryService),
                new DestroyTargetPermanentAndBoostSelfByManaValueEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new DestroyTargetPermanentAndGainLifeEqualToManaValueEffectHandler(destructionSupport, gameQueryService, lifeSupport),
                new DestroyTargetCreatureAndGainLifeEqualToToughnessEffectHandler(destructionSupport, gameQueryService, lifeSupport),
                new SacrificeSelfToDestroyCreatureDamagedPlayerControlsEffectHandler(destructionSupport, gameBroadcastService, gameQueryService, playerInputService),
                new DestroyTargetPermanentAtEndStepEffectHandler(destructionSupport, gameBroadcastService, gameQueryService),
                new SeparatePermanentsIntoPilesAndSacrificeEffectHandler(destructionSupport, gameBroadcastService, playerInputService),
                new AttachTargetToSourcePermanentEffectHandler(gameQueryService, gameBroadcastService),
                new CreateLifeTotalAvatarTokenEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService),
                new CreateTokenCopyOfEquippedCreatureEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService),
                createTokenCopyOfImprintedCardEffectHandler,
                new CreateTokenCopyOfExiledCostCardEffectHandler(createTokenCopyOfImprintedCardEffectHandler),
                new CreateTokenCopyOfSourceEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService),
                new CreateTokenCopyOfTargetPermanentEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService),
                new CreateTokenEffectHandler(permanentControlSupport),
                new CreateTokenForTargetPlayerEffectHandler(permanentControlSupport),
                new CreateTokenFromHalfLifeTotalAndDealDamageEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService, triggerCollectionService),
                new CreateTokenPerAttachmentOnSourceEffectHandler(permanentControlSupport, gameQueryService),
                new CreateTokenPerEquipmentOnSourceEffectHandler(permanentControlSupport, gameQueryService),
                new CreateTokenPerOpponentPoisonCounterEffectHandler(permanentControlSupport),
                new CreateTokensEqualToChargeCountersOnSourceEffectHandler(permanentControlSupport),
                new CreateTokensEqualToControlledCreatureCountEffectHandler(permanentControlSupport, gameQueryService),
                new CreateTokensPerControlledCreatureSubtypeEffectHandler(permanentControlSupport, gameQueryService),
                new CreateTokensPerControlledLandSubtypeEffectHandler(permanentControlSupport),
                new CreateTokensPerCreatureCardInGraveyardEffectHandler(permanentControlSupport),
                new CreateTokensPerOwnCreatureDeathsThisTurnEffectHandler(permanentControlSupport),
                new CreateXCreatureTokenEffectHandler(permanentControlSupport),
                new GainControlOfEnchantedTargetEffectHandler(gameQueryService, gameBroadcastService, creatureControlService),
                new GainControlOfTargetAuraEffectHandler(gameQueryService, gameBroadcastService, playerInputService),
                new GainControlOfTargetPermanentEffectHandler(gameQueryService, gameBroadcastService, creatureControlService),
                new GainControlOfTargetPermanentUntilEndOfTurnEffectHandler(gameQueryService, creatureControlService),
                new GainControlOfTargetPermanentWhileSourceEffectHandler(gameQueryService, gameBroadcastService, creatureControlService),
                new GrantSubtypeToTargetCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new LivingWeaponEffectHandler(battlefieldEntryService, legendRuleService, gameQueryService, gameBroadcastService),
                new PutAuraFromHandOntoSelfEffectHandler(gameBroadcastService, playerInputService),
                new PutSlimeCounterAndCreateOozeTokenEffectHandler(permanentControlSupport, gameQueryService, gameBroadcastService),
                new PutTargetOnBottomOfLibraryEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService),
                new PutTargetOnTopOfLibraryEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService),
                new PutTargetPermanentIntoLibraryNFromTopEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService),
                new RedirectUnblockedCombatDamageToSelfEffectHandler(gameBroadcastService),
                new RegenerateAllOwnCreaturesEffectHandler(gameQueryService, gameBroadcastService),
                new RegenerateEffectHandler(gameQueryService, gameBroadcastService),
                new ReturnSelfToHandAndCreateTokensEffectHandler(permanentControlSupport, gameQueryService, gameBroadcastService, permanentRemovalService),
                new SacrificeAtEndOfCombatEffectHandler(gameQueryService),
                new SacrificeEnchantedCreatureAndCreateTokenEffectHandler(permanentControlSupport, gameQueryService, gameBroadcastService, permanentRemovalService),
                new SacrificeEnchantedCreatureEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService),
                new SacrificeSelfEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService, triggerCollectionService),
                new TargetPlayerGainsControlOfSourceCreatureEffectHandler(gameBroadcastService, creatureControlService),
                new PutXMinusOneMinusOneCountersOnEachCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutXPlusOnePlusOneCountersOnTargetPermanentEffectHandler(gameQueryService, permanentCounterSupport),
                new PutMinusOneMinusOneCounterOnEachOtherCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutMinusOneMinusOneCounterOnEachCreatureTargetPlayerControlsEffectHandler(gameQueryService, gameBroadcastService),
                new PutMinusOneMinusOneCounterOnEachAttackingCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutCountersOnSourceEffectHandler(gameQueryService, gameBroadcastService),
                new PutChargeCounterOnSelfEffectHandler(gameQueryService, gameBroadcastService),
                new PutCounterOnSelfEffectHandler(gameQueryService, gameBroadcastService),
                new PutCountersOnSelfEffectHandler(gameQueryService, permanentCounterSupport),
                new PutCounterOnSelfThenTransformIfThresholdEffectHandler(gameQueryService, gameBroadcastService, permanentCounterSupport),
                new RemoveCountersAndTransformSelfEffectHandler(gameQueryService, permanentCounterSupport),
                putCounterOnTargetPermanentEffectHandler,
                new PutChargeCounterOnTargetPermanentEffectHandler(putCounterOnTargetPermanentEffectHandler),
                new PutPhylacteryCounterOnTargetPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new PutMinusOneMinusOneCounterOnTargetCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new RemoveChargeCountersFromTargetPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new RemoveCountersFromTargetAndBoostSelfEffectHandler(gameQueryService, gameBroadcastService),
                new PutMinusOneMinusOneCounterOnEnchantedCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutPlusOnePlusOneCounterOnEnchantedCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutPlusOnePlusOneCounterOnTargetCreatureEffectHandler(gameQueryService, permanentCounterSupport),
                new PutPlusOnePlusOneCounterOnFirstTargetEffectHandler(gameQueryService, permanentCounterSupport),
                new PutPlusOnePlusOneCounterOnFirstTargetIfSupertypeEffectHandler(gameQueryService, permanentCounterSupport),
                new ChooseOpponentPermanentsAndPutCountersEffectHandler(gameQueryService, gameBroadcastService, playerInputService, permanentCounterSupport),
                new ProliferateEffectHandler(gameBroadcastService, playerInputService),
                new PutPlusOnePlusOneCounterOnEachOwnCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new PutPlusOnePlusOneCounterOnEachControlledPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new UnattachEquipmentFromTargetPermanentsEffectHandler(gameQueryService, gameBroadcastService, permanentRemovalService),
                new OpponentMayPlayCreatureEffectHandler(playerInteractionSupport),
                new PutCardToBattlefieldEffectHandler(playerInteractionSupport),
                new DrawCardEffectHandler(playerInteractionSupport),
                new EachPlayerDrawsCardEffectHandler(playerInteractionSupport),
                new SacrificeSelfAndDrawCardsEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new FlipCoinWinEffectHandler(effectHandlerRegistry, gameBroadcastService, playerInteractionSupport),
                new FlipTwoCoinsEffectHandler(effectHandlerRegistry, gameBroadcastService, playerInteractionSupport),
                new SacrificeSelfAndTargetDiscardsPerPoisonCounterEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new DrawXCardsForTargetPlayerEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawXCardsEffectHandler(playerInteractionSupport),
                new ShuffleHandIntoLibraryAndDrawEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawCardsEqualToChargeCountersOnSourceEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawCardsEqualToControlledCreatureCountEffectHandler(drawService, gameBroadcastService, gameQueryService, playerInteractionSupport),
                new DrawCardsPerCreatureCardInGraveyardEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardCardEffectHandler(playerInteractionSupport),
                new DiscardCardUnlessAttackedThisTurnEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardOwnHandEffectHandler(gameBroadcastService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new DiscardOwnHandThenDrawThatManyEffectHandler(drawService, gameBroadcastService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new DrawDiscardTransformIfCreatureDiscardedEffectHandler(drawService, playerInteractionSupport),
                new DrawAndDiscardCardEffectHandler(playerInteractionSupport),
                new RegisterDelayedCombatDamageLootEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardUnlessExileCardFromGraveyardEffectHandler(gameQueryService, playerInteractionSupport),
                new DiscardUpToThenDrawThatManyEffectHandler(gameBroadcastService, playerInputService, playerInteractionSupport),
                new DiscardAndDrawCardEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardCardAndUntapSelfEffectHandler(gameBroadcastService, playerInteractionSupport),
                new EachPlayerDiscardsEffectHandler(playerInteractionSupport),
                new EachOpponentDiscardsEffectHandler(playerInteractionSupport),
                new TargetPlayerExilesFromHandEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new TargetPlayerDiscardsEffectHandler(playerInteractionSupport),
                new TargetSpellControllerDiscardsEffectHandler(playerInteractionSupport),
                new TargetPlayerDiscardsByChargeCountersEffectHandler(gameBroadcastService, playerInteractionSupport),
                new TargetPlayerDiscardsReturnSelfIfCardTypeEffectHandler(playerInteractionSupport),
                new ChooseCardFromTargetHandToDiscardEffectHandler(playerInteractionSupport),
                new ChooseCardFromTargetHandToExileEffectHandler(playerInteractionSupport),
                new ChooseCardNameAndExileFromZonesEffectHandler(playerInputService, playerInteractionSupport),
                new ExileTargetGraveyardCardAndSameNameFromZonesEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new TargetPlayerRandomDiscardEffectHandler(playerInteractionSupport),
                new DrawAndRandomDiscardWithSharedTypeCountersEffectHandler(drawService, gameBroadcastService, gameQueryService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new TargetPlayerRandomDiscardOrControllerDrawsEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new TargetPlayerRandomDiscardXEffectHandler(gameBroadcastService, playerInteractionSupport),
                new EachPlayerRandomDiscardEffectHandler(playerInteractionSupport),
                new ReturnPermanentsOnCombatDamageToPlayerEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new PutAwakeningCountersOnTargetLandsEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new MayEffectHandler(playerInteractionSupport),
                new MayPayManaEffectHandler(playerInteractionSupport),
                new SacrificeArtifactThenDealDividedDamageEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new SacrificePermanentThenEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new SacrificeCreatureToCreateTokensEqualToToughnessEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new LookAtHandEffectHandler(cardViewFactory, gameBroadcastService, playerInteractionSupport, sessionManager),
                new RevealRandomCardFromTargetPlayerHandEffectHandler(cardViewFactory, gameBroadcastService, playerInteractionSupport, sessionManager),
                new ChooseCardsFromTargetHandToTopOfLibraryEffectHandler(gameBroadcastService, playerInputService, playerInteractionSupport),
                new ChangeColorTextEffectHandler(gameQueryService, playerInteractionSupport, sessionManager),
                new AwardAnyColorManaWithInstantSorceryCopyEffectHandler(playerInteractionSupport, sessionManager),
                new AwardAnyColorManaEffectHandler(playerInteractionSupport, sessionManager),
                new AddManaPerAttackingCreatureEffectHandler(playerInteractionSupport, sessionManager),
                new DrawAndLoseLifePerSubtypeEffectHandler(drawService, gameBroadcastService, gameQueryService, playerInteractionSupport),
                new RedirectDrawsEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DrawCardForTargetPlayerEffectHandler(drawService, gameQueryService, playerInteractionSupport),
                new SacrificeUnlessDiscardCardTypeEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new LoseLifeUnlessDiscardEffectHandler(gameBroadcastService, gameQueryService, playerInteractionSupport),
                new LoseLifeUnlessPaysEffectHandler(gameBroadcastService, gameQueryService, playerInteractionSupport),
                new SacrificeUnlessReturnOwnPermanentTypeToHandEffectHandler(gameBroadcastService, permanentRemovalService, playerInteractionSupport),
                new GrantPermanentNoMaxHandSizeEffectHandler(gameBroadcastService, playerInteractionSupport),
                new RevealRandomHandCardAndPlayEffectHandler(battlefieldEntryService, cardViewFactory, gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport, sessionManager, triggerCollectionService),
                new TapCreaturesEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new TapAllAttackingCreaturesEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new SkipNextUntapAllAttackingCreaturesEffectHandler(gameQueryService, gameBroadcastService),
                new TapSelfEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new TapEnchantedCreatureEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new TapOrUntapTargetPermanentEffectHandler(gameQueryService, gameBroadcastService, triggerCollectionService),
                new TapTargetPermanentEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new SkipNextUntapOnTargetEffectHandler(gameQueryService, gameBroadcastService),
                new PreventTargetUntapWhileSourceTappedEffectHandler(gameQueryService, gameBroadcastService),
                new PreventTargetUntapWhileSourceOnBattlefieldEffectHandler(gameQueryService, gameBroadcastService),
                new UntapAllTargetPermanentsEffectHandler(gameQueryService, gameBroadcastService),
                new UntapTargetPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new RemoveTargetFromCombatEffectHandler(gameQueryService, gameBroadcastService),
                new UntapSelfEffectHandler(gameQueryService, gameBroadcastService),
                new UntapAttackedCreaturesEffectHandler(gameQueryService, gameBroadcastService),
                new UntapEachOtherCreatureYouControlEffectHandler(gameQueryService, gameBroadcastService),
                new TapPermanentsOfTargetPlayerEffectHandler(gameQueryService, gameBroadcastService, tapUntapSupport),
                new SkipNextUntapPermanentsOfTargetPlayerEffectHandler(gameQueryService, gameBroadcastService),
                new UntapAllControlledPermanentsEffectHandler(gameQueryService, gameBroadcastService),
                new RegisterDelayedUntapPermanentsEffectHandler(),
                new UntapUpToControlledPermanentsEffectHandler(gameQueryService, gameBroadcastService),
                new GrantKeywordEffectHandler(gameQueryService, gameBroadcastService),
                new GrantKeywordToTargetIfSupertypeEffectHandler(gameQueryService, gameBroadcastService),
                new GrantKeywordToTargetIfPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new GrantChosenKeywordToTargetEffectHandler(gameQueryService, playerInputService),
                new GrantColorUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantKeywordToChosenCreatureUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantProtectionChoiceUntilEndOfTurnEffectHandler(gameQueryService, playerInputService),
                new GrantProtectionChoiceToControllerAndPermanentsUntilEndOfTurnEffectHandler(playerInputService),
                new GrantProtectionFromCardTypeUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new RemoveKeywordEffectHandler(gameQueryService, gameBroadcastService),
                new LosesAllAbilitiesEffectHandler(gameQueryService, gameBroadcastService),
                new GrantFlashbackToGraveyardCardsEffectHandler(gameBroadcastService),
                new GrantFlashbackToTargetGraveyardCardEffectHandler(gameQueryService, gameBroadcastService),
                new GrantTargetCreatureCardGraveyardCastAndCopyActivatedAbilitiesEffectHandler(gameQueryService, gameBroadcastService),
                new GrantSourceActivatedAbilitiesUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantProtectionFromNonSubtypeCreaturesUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantDamageToOpponentCreatureBounceUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantEffectToTargetUntilEndOfTurnEffectHandler(gameQueryService, gameBroadcastService),
                new GrantActivatedAbilityEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateLandEffectHandler(animationSupport),
                new AnimateControlledPermanentsEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateSelfAsCreatureEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateSelfEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateSelfByChargeCountersEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateSelfWithStatsEffectHandler(gameQueryService, gameBroadcastService),
                new AddCardTypeToTargetPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new AnimateTargetPermanentEffectHandler(gameQueryService, gameBroadcastService),
                new TransformSelfEffectHandler(gameQueryService, animationSupport),
                new TransformSelfAndAttachToCreatureDamagedPlayerControlsEffectHandler(gameQueryService, gameBroadcastService, playerInputService),
                new TransformAllEffectHandler(gameQueryService, gameBroadcastService),
                new TapAndTransformSelfEffectHandler(gameQueryService, gameBroadcastService),
                new GrantBasicLandTypeToTargetEffectHandler(gameQueryService, playerInputService),
                new AnimateTargetLandWhileSourceOnBattlefieldEffectHandler(gameQueryService, gameBroadcastService),
                new WarpWorldEffectHandler(warpWorldService, battlefieldEntryService, gameQueryService),
                new GenesisWaveEffectHandler(graveyardService, gameBroadcastService, sessionManager, cardViewFactory),
                new KothEmblemEffectHandler(gameBroadcastService),
                new VenserEmblemEffectHandler(gameBroadcastService),
                new JayaBallardEmblemEffectHandler(gameBroadcastService),
                new TeferiHeroEmblemEffectHandler(gameBroadcastService),
                new SorinLordOfInnistradEmblemEffectHandler(gameBroadcastService),
                new SacrificeTargetThenRevealUntilTypeToBattlefieldEffectHandler(gameQueryService, permanentRemovalService, gameBroadcastService, battlefieldEntryService, legendRuleService, cardSpecificSupport),
                new DestroyTargetThenRevealUntilTypeToBattlefieldEffectHandler(gameQueryService, permanentRemovalService, gameBroadcastService, battlefieldEntryService, legendRuleService, cardSpecificSupport),
                new ExileAllCreaturesYouControlThenRevealCreaturesToBattlefieldEffectHandler(permanentRemovalService, gameBroadcastService, battlefieldEntryService, legendRuleService, cardSpecificSupport),
                new ShuffleSelfIntoOwnerLibraryRevealUntilNameToBattlefieldEffectHandler(gameQueryService, permanentRemovalService, gameBroadcastService, battlefieldEntryService, graveyardService, legendRuleService),
                new KarnRestartGameEffectHandler(gameBroadcastService),
                new KarnScionRevealTwoOpponentChoosesEffectHandler(gameBroadcastService),
                new KarnScionReturnSilverCounterCardEffectHandler(gameBroadcastService),
                new ReturnCardFromGraveyardEffectHandler(playerInputService, graveyardReturnSupport),
                new PutTargetCardsFromGraveyardOnTopOfLibraryEffectHandler(graveyardReturnSupport),
                new ReturnTargetCardsFromGraveyardToHandEffectHandler(graveyardReturnSupport),
                new DestroyUpToTargetsThenReturnFromGraveyardEffectHandler(battlefieldEntryService, permanentRemovalService, gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new UndyingReturnEffectHandler(battlefieldEntryService, permanentRemovalService, gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new PutCardFromOpponentGraveyardOntoBattlefieldEffectHandler(battlefieldEntryService, gameBroadcastService, graveyardReturnSupport),
                new PutCreatureFromOpponentGraveyardOntoBattlefieldWithExileEffectHandler(battlefieldEntryService, gameBroadcastService, graveyardReturnSupport),
                new ExileCardsFromGraveyardEffectHandler(gameQueryService, gameBroadcastService, lifeSupport, graveyardReturnSupport),
                new ExileTargetCardFromGraveyardAndImprintOnSourceEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService, exileService),
                new ExileTargetCardFromGraveyardEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService, exileService),
                new ExileTargetCardFromGraveyardAndCreateTokenCopyEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService, exileService, graveyardReturnSupport),
                new ExileGraveyardCardWithConditionalBonusEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService, lifeSupport, exileService),
                new ExileTargetCardsFromOpponentGraveyardEffectHandler(gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new ExileCreaturesFromGraveyardAndCreateTokensEffectHandler(battlefieldEntryService, gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new ExileTargetPlayerGraveyardEffectHandler(gameBroadcastService),
                new ExileAllOpponentsGraveyardsEffectHandler(gameBroadcastService),
                new ExileNonBasicLandGraveyardAndSameNameFromLibraryEffectHandler(gameBroadcastService),
                new PutImprintedCreatureOntoBattlefieldEffectHandler(battlefieldEntryService, gameBroadcastService, graveyardReturnSupport),
                new PutImprintedCardIntoOwnersHandEffectHandler(gameBroadcastService),
                new ReturnDyingCreatureToBattlefieldAndAttachSourceEffectHandler(battlefieldEntryService, permanentRemovalService, gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new CastTargetInstantOrSorceryFromGraveyardEffectHandler(gameQueryService, gameBroadcastService),
                new ReturnSourceAuraToOpponentCreatureOnDeathEffectHandler(battlefieldEntryService, permanentRemovalService, gameQueryService, gameBroadcastService, playerInputService),
                new ReturnEnchantedCreatureToOwnerHandOnDeathEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService),
                new ReturnSourceCardFromGraveyardToOwnerHandEffectHandler(permanentRemovalService, gameQueryService, gameBroadcastService),
                new ExileCardsFromOwnGraveyardEffectHandler(gameBroadcastService, exileService, graveyardReturnSupport),
                new TargetPlayerExilesCardFromGraveyardEffectHandler(gameBroadcastService, playerInputService, lifeSupport, exileService),
                new EachPlayerReturnsCardsFromGraveyardToBattlefieldEffectHandler(gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new ReturnOneOfEachSubtypeFromGraveyardToHandEffectHandler(gameQueryService, gameBroadcastService, graveyardReturnSupport),
                new RegisterDelayedReturnCardFromGraveyardToHandEffectHandler(gameBroadcastService),
                new RegisterDelayedReturnSourceTransformedEffectHandler(gameQueryService, gameBroadcastService),
                new ExileTargetGraveyardCardsAndSeparateIntoPilesEffectHandler(gameQueryService, gameBroadcastService, playerInputService, cardViewFactory)
        );
    }


    /** Player-interaction handlers only — for unit tests and focused wiring. */
    public static List<NormalEffectHandlerBean> createPlayerInteractionHandlers(
            PlayerInteractionSupport playerInteractionSupport,
            DrawService drawService,
            GraveyardService graveyardService,
            GameQueryService gameQueryService,
            GameBroadcastService gameBroadcastService,
            PlayerInputService playerInputService,
            SessionManager sessionManager,
            CardViewFactory cardViewFactory,
            PermanentRemovalService permanentRemovalService,
            BattlefieldEntryService battlefieldEntryService,
            TriggerCollectionService triggerCollectionService,
            EffectHandlerRegistry effectHandlerRegistry) {
        return List.of(
                new OpponentMayPlayCreatureEffectHandler(playerInteractionSupport),
                new PutCardToBattlefieldEffectHandler(playerInteractionSupport),
                new DrawCardEffectHandler(playerInteractionSupport),
                new EachPlayerDrawsCardEffectHandler(playerInteractionSupport),
                new SacrificeSelfAndDrawCardsEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new FlipCoinWinEffectHandler(effectHandlerRegistry, gameBroadcastService, playerInteractionSupport),
                new FlipTwoCoinsEffectHandler(effectHandlerRegistry, gameBroadcastService, playerInteractionSupport),
                new SacrificeSelfAndTargetDiscardsPerPoisonCounterEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new DrawXCardsForTargetPlayerEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawXCardsEffectHandler(playerInteractionSupport),
                new ShuffleHandIntoLibraryAndDrawEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawCardsEqualToChargeCountersOnSourceEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new DrawCardsEqualToControlledCreatureCountEffectHandler(drawService, gameBroadcastService, gameQueryService, playerInteractionSupport),
                new DrawCardsPerCreatureCardInGraveyardEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardCardEffectHandler(playerInteractionSupport),
                new DiscardCardUnlessAttackedThisTurnEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardOwnHandEffectHandler(gameBroadcastService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new DiscardOwnHandThenDrawThatManyEffectHandler(drawService, gameBroadcastService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new DrawDiscardTransformIfCreatureDiscardedEffectHandler(drawService, playerInteractionSupport),
                new DrawAndDiscardCardEffectHandler(playerInteractionSupport),
                new RegisterDelayedCombatDamageLootEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardUnlessExileCardFromGraveyardEffectHandler(gameQueryService, playerInteractionSupport),
                new DiscardUpToThenDrawThatManyEffectHandler(gameBroadcastService, playerInputService, playerInteractionSupport),
                new DiscardAndDrawCardEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DiscardCardAndUntapSelfEffectHandler(gameBroadcastService, playerInteractionSupport),
                new EachPlayerDiscardsEffectHandler(playerInteractionSupport),
                new EachOpponentDiscardsEffectHandler(playerInteractionSupport),
                new TargetPlayerExilesFromHandEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new TargetPlayerDiscardsEffectHandler(playerInteractionSupport),
                new TargetSpellControllerDiscardsEffectHandler(playerInteractionSupport),
                new TargetPlayerDiscardsByChargeCountersEffectHandler(gameBroadcastService, playerInteractionSupport),
                new TargetPlayerDiscardsReturnSelfIfCardTypeEffectHandler(playerInteractionSupport),
                new ChooseCardFromTargetHandToDiscardEffectHandler(playerInteractionSupport),
                new ChooseCardFromTargetHandToExileEffectHandler(playerInteractionSupport),
                new ChooseCardNameAndExileFromZonesEffectHandler(playerInputService, playerInteractionSupport),
                new ExileTargetGraveyardCardAndSameNameFromZonesEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new TargetPlayerRandomDiscardEffectHandler(playerInteractionSupport),
                new DrawAndRandomDiscardWithSharedTypeCountersEffectHandler(drawService, gameBroadcastService, gameQueryService, graveyardService, playerInteractionSupport, triggerCollectionService),
                new TargetPlayerRandomDiscardOrControllerDrawsEffectHandler(drawService, gameBroadcastService, playerInteractionSupport),
                new TargetPlayerRandomDiscardXEffectHandler(gameBroadcastService, playerInteractionSupport),
                new EachPlayerRandomDiscardEffectHandler(playerInteractionSupport),
                new ReturnPermanentsOnCombatDamageToPlayerEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new PutAwakeningCountersOnTargetLandsEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new MayEffectHandler(playerInteractionSupport),
                new MayPayManaEffectHandler(playerInteractionSupport),
                new SacrificeArtifactThenDealDividedDamageEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new SacrificePermanentThenEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new SacrificeCreatureToCreateTokensEqualToToughnessEffectHandler(gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport),
                new LookAtHandEffectHandler(cardViewFactory, gameBroadcastService, playerInteractionSupport, sessionManager),
                new RevealRandomCardFromTargetPlayerHandEffectHandler(cardViewFactory, gameBroadcastService, playerInteractionSupport, sessionManager),
                new ChooseCardsFromTargetHandToTopOfLibraryEffectHandler(gameBroadcastService, playerInputService, playerInteractionSupport),
                new ChangeColorTextEffectHandler(gameQueryService, playerInteractionSupport, sessionManager),
                new AwardAnyColorManaWithInstantSorceryCopyEffectHandler(playerInteractionSupport, sessionManager),
                new AwardAnyColorManaEffectHandler(playerInteractionSupport, sessionManager),
                new AddManaPerAttackingCreatureEffectHandler(playerInteractionSupport, sessionManager),
                new DrawAndLoseLifePerSubtypeEffectHandler(drawService, gameBroadcastService, gameQueryService, playerInteractionSupport),
                new RedirectDrawsEffectHandler(gameBroadcastService, playerInteractionSupport),
                new DrawCardForTargetPlayerEffectHandler(drawService, gameQueryService, playerInteractionSupport),
                new SacrificeUnlessDiscardCardTypeEffectHandler(gameBroadcastService, gameQueryService, permanentRemovalService, playerInteractionSupport),
                new LoseLifeUnlessDiscardEffectHandler(gameBroadcastService, gameQueryService, playerInteractionSupport),
                new LoseLifeUnlessPaysEffectHandler(gameBroadcastService, gameQueryService, playerInteractionSupport),
                new SacrificeUnlessReturnOwnPermanentTypeToHandEffectHandler(gameBroadcastService, permanentRemovalService, playerInteractionSupport),
                new GrantPermanentNoMaxHandSizeEffectHandler(gameBroadcastService, playerInteractionSupport),
                new RevealRandomHandCardAndPlayEffectHandler(battlefieldEntryService, cardViewFactory, gameBroadcastService, gameQueryService, playerInputService, playerInteractionSupport, sessionManager, triggerCollectionService)
        );
    }

    public static void registerAll(List<NormalEffectHandlerBean> beans, EffectHandlerRegistry registry) {
        for (NormalEffectHandlerBean bean : beans) {
            registry.register(bean.handledEffect(), bean);
        }
    }
}
