package com.github.laxika.magicalvibes.cards.s;

import com.github.laxika.magicalvibes.model.Card;
import com.github.laxika.magicalvibes.model.EffectSlot;
import com.github.laxika.magicalvibes.model.ManaColor;
import com.github.laxika.magicalvibes.model.effect.AwardManaEffect;
import com.github.laxika.magicalvibes.cards.CardRegistration;

@CardRegistration(set = "10E", collectorNumber = "372")
@CardRegistration(set = "10E", collectorNumber = "373")
@CardRegistration(set = "10E", collectorNumber = "374")
@CardRegistration(set = "10E", collectorNumber = "375")
@CardRegistration(set = "M10", collectorNumber = "238")
@CardRegistration(set = "M10", collectorNumber = "239")
@CardRegistration(set = "M10", collectorNumber = "240")
@CardRegistration(set = "M10", collectorNumber = "241")
@CardRegistration(set = "SOM", collectorNumber = "238")
@CardRegistration(set = "SOM", collectorNumber = "239")
@CardRegistration(set = "SOM", collectorNumber = "240")
@CardRegistration(set = "SOM", collectorNumber = "241")
@CardRegistration(set = "MBS", collectorNumber = "150")
@CardRegistration(set = "MBS", collectorNumber = "151")
@CardRegistration(set = "NPH", collectorNumber = "170")
@CardRegistration(set = "NPH", collectorNumber = "171")
@CardRegistration(set = "M11", collectorNumber = "238")
@CardRegistration(set = "M11", collectorNumber = "239")
@CardRegistration(set = "M11", collectorNumber = "240")
@CardRegistration(set = "M11", collectorNumber = "241")
@CardRegistration(set = "ISD", collectorNumber = "256")
@CardRegistration(set = "ISD", collectorNumber = "257")
@CardRegistration(set = "ISD", collectorNumber = "258")
@CardRegistration(set = "DOM", collectorNumber = "258")
@CardRegistration(set = "DOM", collectorNumber = "259")
@CardRegistration(set = "DOM", collectorNumber = "260")
@CardRegistration(set = "DOM", collectorNumber = "261")
@CardRegistration(set = "XLN", collectorNumber = "268")
@CardRegistration(set = "XLN", collectorNumber = "269")
@CardRegistration(set = "XLN", collectorNumber = "270")
@CardRegistration(set = "XLN", collectorNumber = "271")
@CardRegistration(set = "SOS", collectorNumber = "269")
@CardRegistration(set = "SOS", collectorNumber = "276")
@CardRegistration(set = "SOS", collectorNumber = "277")
@CardRegistration(set = "8ED", collectorNumber = "339")
@CardRegistration(set = "9ED", collectorNumber = "339")
@CardRegistration(set = "9ED", collectorNumber = "340")
@CardRegistration(set = "9ED", collectorNumber = "341")
@CardRegistration(set = "9ED", collectorNumber = "342")
@CardRegistration(set = "POR", collectorNumber = "204")
@CardRegistration(set = "POR", collectorNumber = "205")
@CardRegistration(set = "POR", collectorNumber = "206")
@CardRegistration(set = "POR", collectorNumber = "207")
@CardRegistration(set = "LRW", collectorNumber = "290")
@CardRegistration(set = "LRW", collectorNumber = "291")
@CardRegistration(set = "LRW", collectorNumber = "292")
@CardRegistration(set = "LRW", collectorNumber = "293")
@CardRegistration(set = "P02", collectorNumber = "157")
@CardRegistration(set = "P02", collectorNumber = "158")
@CardRegistration(set = "P02", collectorNumber = "159")
@CardRegistration(set = "PTK", collectorNumber = "172")
@CardRegistration(set = "PTK", collectorNumber = "173")
@CardRegistration(set = "PTK", collectorNumber = "174")
@CardRegistration(set = "6ED", collectorNumber = "339")
@CardRegistration(set = "6ED", collectorNumber = "340")
@CardRegistration(set = "6ED", collectorNumber = "341")
@CardRegistration(set = "6ED", collectorNumber = "342")
@CardRegistration(set = "8ED", collectorNumber = "340")
@CardRegistration(set = "8ED", collectorNumber = "341")
@CardRegistration(set = "8ED", collectorNumber = "342")
@CardRegistration(set = "SHM", collectorNumber = "290")
@CardRegistration(set = "SHM", collectorNumber = "291")
@CardRegistration(set = "SHM", collectorNumber = "292")
@CardRegistration(set = "SHM", collectorNumber = "293")
@CardRegistration(set = "7ED", collectorNumber = "346")
@CardRegistration(set = "7ED", collectorNumber = "347")
@CardRegistration(set = "7ED", collectorNumber = "348")
@CardRegistration(set = "7ED", collectorNumber = "349")
@CardRegistration(set = "ALA", collectorNumber = "238")
@CardRegistration(set = "ALA", collectorNumber = "239")
@CardRegistration(set = "ALA", collectorNumber = "240")
@CardRegistration(set = "ALA", collectorNumber = "241")
public class Swamp extends Card {

    public Swamp() {
        addEffect(EffectSlot.ON_TAP, new AwardManaEffect(ManaColor.BLACK));
    }
}
