package com.github.laxika.magicalvibes.cards.p;

import com.github.laxika.magicalvibes.model.Card;
import com.github.laxika.magicalvibes.model.EffectSlot;
import com.github.laxika.magicalvibes.model.ManaColor;
import com.github.laxika.magicalvibes.model.effect.AwardManaEffect;
import com.github.laxika.magicalvibes.cards.CardRegistration;

@CardRegistration(set = "10E", collectorNumber = "364")
@CardRegistration(set = "10E", collectorNumber = "365")
@CardRegistration(set = "10E", collectorNumber = "366")
@CardRegistration(set = "10E", collectorNumber = "367")
@CardRegistration(set = "M10", collectorNumber = "230")
@CardRegistration(set = "M10", collectorNumber = "231")
@CardRegistration(set = "M10", collectorNumber = "232")
@CardRegistration(set = "M10", collectorNumber = "233")
@CardRegistration(set = "SOM", collectorNumber = "230")
@CardRegistration(set = "SOM", collectorNumber = "231")
@CardRegistration(set = "SOM", collectorNumber = "232")
@CardRegistration(set = "SOM", collectorNumber = "233")
@CardRegistration(set = "MBS", collectorNumber = "146")
@CardRegistration(set = "MBS", collectorNumber = "147")
@CardRegistration(set = "NPH", collectorNumber = "166")
@CardRegistration(set = "NPH", collectorNumber = "167")
@CardRegistration(set = "M11", collectorNumber = "230")
@CardRegistration(set = "M11", collectorNumber = "231")
@CardRegistration(set = "M11", collectorNumber = "232")
@CardRegistration(set = "M11", collectorNumber = "233")
@CardRegistration(set = "ISD", collectorNumber = "250")
@CardRegistration(set = "ISD", collectorNumber = "251")
@CardRegistration(set = "ISD", collectorNumber = "252")
@CardRegistration(set = "DOM", collectorNumber = "250")
@CardRegistration(set = "DOM", collectorNumber = "251")
@CardRegistration(set = "DOM", collectorNumber = "252")
@CardRegistration(set = "DOM", collectorNumber = "253")
@CardRegistration(set = "XLN", collectorNumber = "260")
@CardRegistration(set = "XLN", collectorNumber = "261")
@CardRegistration(set = "XLN", collectorNumber = "262")
@CardRegistration(set = "XLN", collectorNumber = "263")
@CardRegistration(set = "SOS", collectorNumber = "267")
@CardRegistration(set = "SOS", collectorNumber = "272")
@CardRegistration(set = "SOS", collectorNumber = "273")
@CardRegistration(set = "8ED", collectorNumber = "331")
@CardRegistration(set = "8ED", collectorNumber = "332")
@CardRegistration(set = "8ED", collectorNumber = "333")
@CardRegistration(set = "8ED", collectorNumber = "334")
@CardRegistration(set = "9ED", collectorNumber = "331")
@CardRegistration(set = "9ED", collectorNumber = "332")
@CardRegistration(set = "9ED", collectorNumber = "333")
@CardRegistration(set = "9ED", collectorNumber = "334")
@CardRegistration(set = "POR", collectorNumber = "196")
@CardRegistration(set = "POR", collectorNumber = "197")
@CardRegistration(set = "POR", collectorNumber = "198")
@CardRegistration(set = "POR", collectorNumber = "199")
@CardRegistration(set = "LRW", collectorNumber = "282")
@CardRegistration(set = "LRW", collectorNumber = "283")
@CardRegistration(set = "LRW", collectorNumber = "284")
@CardRegistration(set = "LRW", collectorNumber = "285")
@CardRegistration(set = "P02", collectorNumber = "151")
@CardRegistration(set = "P02", collectorNumber = "152")
@CardRegistration(set = "P02", collectorNumber = "153")
@CardRegistration(set = "PTK", collectorNumber = "166")
@CardRegistration(set = "PTK", collectorNumber = "167")
@CardRegistration(set = "PTK", collectorNumber = "168")
@CardRegistration(set = "SHM", collectorNumber = "282")
@CardRegistration(set = "SHM", collectorNumber = "283")
@CardRegistration(set = "SHM", collectorNumber = "284")
@CardRegistration(set = "SHM", collectorNumber = "285")
@CardRegistration(set = "7ED", collectorNumber = "341")
@CardRegistration(set = "7ED", collectorNumber = "342")
@CardRegistration(set = "7ED", collectorNumber = "343")
@CardRegistration(set = "7ED", collectorNumber = "344")
@CardRegistration(set = "6ED", collectorNumber = "331")
@CardRegistration(set = "6ED", collectorNumber = "332")
@CardRegistration(set = "6ED", collectorNumber = "333")
@CardRegistration(set = "6ED", collectorNumber = "334")
@CardRegistration(set = "ALA", collectorNumber = "230")
@CardRegistration(set = "ALA", collectorNumber = "231")
@CardRegistration(set = "ALA", collectorNumber = "232")
@CardRegistration(set = "ALA", collectorNumber = "233")
@CardRegistration(set = "5ED", collectorNumber = "430")
@CardRegistration(set = "5ED", collectorNumber = "431")
@CardRegistration(set = "5ED", collectorNumber = "432")
@CardRegistration(set = "5ED", collectorNumber = "433")
@CardRegistration(set = "4ED", collectorNumber = "364")
@CardRegistration(set = "4ED", collectorNumber = "365")
@CardRegistration(set = "4ED", collectorNumber = "366")
@CardRegistration(set = "AKH", collectorNumber = "250")
@CardRegistration(set = "AKH", collectorNumber = "255")
@CardRegistration(set = "AKH", collectorNumber = "256")
@CardRegistration(set = "AKH", collectorNumber = "257")
@CardRegistration(set = "HOU", collectorNumber = "185")
@CardRegistration(set = "HOU", collectorNumber = "190")
@CardRegistration(set = "HOU", collectorNumber = "191")
public class Plains extends Card {

    public Plains() {
        addEffect(EffectSlot.ON_TAP, new AwardManaEffect(ManaColor.WHITE));
    }
}
