package com.github.laxika.magicalvibes.cards.a;

import com.github.laxika.magicalvibes.cards.CardRegistration;
import com.github.laxika.magicalvibes.model.Card;
import com.github.laxika.magicalvibes.model.ManaAbilities;

@CardRegistration(set = "SLD", collectorNumber = "201")
@CardRegistration(set = "SLD", collectorNumber = "589")
@CardRegistration(set = "SLD", collectorNumber = "820")
@CardRegistration(set = "SLD", collectorNumber = "908")
@CardRegistration(set = "SLD", collectorNumber = "916")
@CardRegistration(set = "SLD", collectorNumber = "1492")
@CardRegistration(set = "SLD", collectorNumber = "1641")
@CardRegistration(set = "SLD", collectorNumber = "1919")
@CardRegistration(set = "SLD", collectorNumber = "1924")
@CardRegistration(set = "SLD", collectorNumber = "2464")
@CardRegistration(set = "ANB", collectorNumber = "117")
@CardRegistration(set = "SOC", collectorNumber = "127")
@CardRegistration(set = "MSC", collectorNumber = "191")
@CardRegistration(set = "MSC", collectorNumber = "192")
@CardRegistration(set = "MSC", collectorNumber = "193")
@CardRegistration(set = "MSC", collectorNumber = "194")
@CardRegistration(set = "TLE", collectorNumber = "315")
@CardRegistration(set = "TMC", collectorNumber = "57")
@CardRegistration(set = "HOC", collectorNumber = "95")
@CardRegistration(set = "SLZ", collectorNumber = "94")
@CardRegistration(set = "SLZ", collectorNumber = "215")
@CardRegistration(set = "SLZ", collectorNumber = "336")
@CardRegistration(set = "ECC", collectorNumber = "55")
@CardRegistration(set = "ECC", collectorNumber = "56")
@CardRegistration(set = "CMM", collectorNumber = "367")
@CardRegistration(set = "CMM", collectorNumber = "653")
@CardRegistration(set = "WHO", collectorNumber = "239")
@CardRegistration(set = "WHO", collectorNumber = "830")
@CardRegistration(set = "PIP", collectorNumber = "224")
@CardRegistration(set = "PIP", collectorNumber = "356")
@CardRegistration(set = "PIP", collectorNumber = "752")
@CardRegistration(set = "PIP", collectorNumber = "884")
@CardRegistration(set = "MB2", collectorNumber = "254")
@CardRegistration(set = "FIC", collectorNumber = "332")
@CardRegistration(set = "FIC", collectorNumber = "333")
@CardRegistration(set = "FIC", collectorNumber = "334")
@CardRegistration(set = "FIC", collectorNumber = "335")
@CardRegistration(set = "MOC", collectorNumber = "348")
@CardRegistration(set = "C20", collectorNumber = "237")
@CardRegistration(set = "C21", collectorNumber = "234")
@CardRegistration(set = "40K", collectorNumber = "227")
@CardRegistration(set = "40K", collectorNumber = "228")
@CardRegistration(set = "40K", collectorNumber = "229")
@CardRegistration(set = "DSC", collectorNumber = "92")
@CardRegistration(set = "LTC", collectorNumber = "273")
@CardRegistration(set = "TDC", collectorNumber = "105")
@CardRegistration(set = "M3C", collectorNumber = "283")
@CardRegistration(set = "MKC", collectorNumber = "223")
@CardRegistration(set = "AFC", collectorNumber = "197")
@CardRegistration(set = "OTC", collectorNumber = "252")
@CardRegistration(set = "LCC", collectorNumber = "104")
@CardRegistration(set = "LCC", collectorNumber = "299")
@CardRegistration(set = "DMC", collectorNumber = "177")
@CardRegistration(set = "BLC", collectorNumber = "127")
@CardRegistration(set = "MIC", collectorNumber = "157")
@CardRegistration(set = "NEC", collectorNumber = "144")
@CardRegistration(set = "BRC", collectorNumber = "132")
@CardRegistration(set = "ONC", collectorNumber = "125")
@CardRegistration(set = "WOC", collectorNumber = "145")
@CardRegistration(set = "VOC", collectorNumber = "159")
@CardRegistration(set = "DRC", collectorNumber = "51")
@CardRegistration(set = "DRC", collectorNumber = "52")
public class ArcaneSignet extends Card {

    public ArcaneSignet() {
        addActivatedAbility(ManaAbilities.tapForAnyColor());
    }
}
