package com.github.laxika.magicalvibes.cards.i;

import com.github.laxika.magicalvibes.model.Card;
import com.github.laxika.magicalvibes.model.EffectSlot;
import com.github.laxika.magicalvibes.model.ManaColor;
import com.github.laxika.magicalvibes.model.effect.AwardManaEffect;
import com.github.laxika.magicalvibes.cards.CardRegistration;

@CardRegistration(set = "10E", collectorNumber = "368")
@CardRegistration(set = "10E", collectorNumber = "369")
@CardRegistration(set = "10E", collectorNumber = "370")
@CardRegistration(set = "10E", collectorNumber = "371")
@CardRegistration(set = "M10", collectorNumber = "234")
@CardRegistration(set = "M10", collectorNumber = "235")
@CardRegistration(set = "M10", collectorNumber = "236")
@CardRegistration(set = "M10", collectorNumber = "237")
@CardRegistration(set = "SOM", collectorNumber = "234")
@CardRegistration(set = "SOM", collectorNumber = "235")
@CardRegistration(set = "SOM", collectorNumber = "236")
@CardRegistration(set = "SOM", collectorNumber = "237")
@CardRegistration(set = "MBS", collectorNumber = "148")
@CardRegistration(set = "MBS", collectorNumber = "149")
@CardRegistration(set = "NPH", collectorNumber = "168")
@CardRegistration(set = "NPH", collectorNumber = "169")
@CardRegistration(set = "M11", collectorNumber = "234")
@CardRegistration(set = "M11", collectorNumber = "235")
@CardRegistration(set = "M11", collectorNumber = "236")
@CardRegistration(set = "M11", collectorNumber = "237")
@CardRegistration(set = "ISD", collectorNumber = "253")
@CardRegistration(set = "ISD", collectorNumber = "254")
@CardRegistration(set = "ISD", collectorNumber = "255")
@CardRegistration(set = "DOM", collectorNumber = "254")
@CardRegistration(set = "DOM", collectorNumber = "255")
@CardRegistration(set = "DOM", collectorNumber = "256")
@CardRegistration(set = "DOM", collectorNumber = "257")
@CardRegistration(set = "XLN", collectorNumber = "264")
@CardRegistration(set = "XLN", collectorNumber = "265")
@CardRegistration(set = "XLN", collectorNumber = "266")
@CardRegistration(set = "XLN", collectorNumber = "267")
@CardRegistration(set = "SOS", collectorNumber = "268")
@CardRegistration(set = "SOS", collectorNumber = "274")
@CardRegistration(set = "SOS", collectorNumber = "275")
@CardRegistration(set = "8ED", collectorNumber = "335")
@CardRegistration(set = "8ED", collectorNumber = "336")
@CardRegistration(set = "8ED", collectorNumber = "337")
@CardRegistration(set = "8ED", collectorNumber = "338")
@CardRegistration(set = "9ED", collectorNumber = "335")
@CardRegistration(set = "9ED", collectorNumber = "336")
@CardRegistration(set = "9ED", collectorNumber = "337")
@CardRegistration(set = "9ED", collectorNumber = "338")
@CardRegistration(set = "POR", collectorNumber = "200")
@CardRegistration(set = "POR", collectorNumber = "201")
@CardRegistration(set = "POR", collectorNumber = "202")
@CardRegistration(set = "POR", collectorNumber = "203")
@CardRegistration(set = "SHM", collectorNumber = "286")
@CardRegistration(set = "SHM", collectorNumber = "287")
@CardRegistration(set = "SHM", collectorNumber = "288")
@CardRegistration(set = "SHM", collectorNumber = "289")
@CardRegistration(set = "LRW", collectorNumber = "286")
@CardRegistration(set = "LRW", collectorNumber = "287")
@CardRegistration(set = "LRW", collectorNumber = "288")
@CardRegistration(set = "LRW", collectorNumber = "289")
@CardRegistration(set = "P02", collectorNumber = "154")
@CardRegistration(set = "P02", collectorNumber = "155")
@CardRegistration(set = "P02", collectorNumber = "156")
@CardRegistration(set = "PTK", collectorNumber = "169")
@CardRegistration(set = "PTK", collectorNumber = "170")
@CardRegistration(set = "PTK", collectorNumber = "171")
@CardRegistration(set = "7ED", collectorNumber = "332")
@CardRegistration(set = "7ED", collectorNumber = "333")
@CardRegistration(set = "7ED", collectorNumber = "334")
@CardRegistration(set = "7ED", collectorNumber = "335")
@CardRegistration(set = "6ED", collectorNumber = "335")
@CardRegistration(set = "6ED", collectorNumber = "336")
@CardRegistration(set = "6ED", collectorNumber = "337")
@CardRegistration(set = "6ED", collectorNumber = "338")
@CardRegistration(set = "ALA", collectorNumber = "234")
@CardRegistration(set = "ALA", collectorNumber = "235")
@CardRegistration(set = "ALA", collectorNumber = "236")
@CardRegistration(set = "ALA", collectorNumber = "237")
@CardRegistration(set = "5ED", collectorNumber = "434")
@CardRegistration(set = "5ED", collectorNumber = "435")
@CardRegistration(set = "5ED", collectorNumber = "436")
@CardRegistration(set = "5ED", collectorNumber = "437")
public class Island extends Card {

    public Island() {
        addEffect(EffectSlot.ON_TAP, new AwardManaEffect(ManaColor.BLUE));
    }
}
