server.address=127.0.0.1
server.port=8091
spring.application.name=magical-vibes-review-server
spring.liquibase.change-log=classpath:review-db/changelog/master.yaml
spring.jackson.serialization.indent-output=true
review.repository-root=${REVIEW_REPOSITORY_ROOT:}
review.database-path=${REVIEW_DATABASE_PATH:magical-vibes-review-server/review.sqlite}
