package com.github.laxika.magicalvibes.model;

public enum ActivationTimingRestriction {
    CAST_NONCREATURE_SPELL_THIS_TURN,
    METALCRAFT,
    MORBID,
    ONLY_BEFORE_ATTACKERS_DECLARED,
    ONLY_DURING_DECLARE_ATTACKERS_IF_ATTACKED,
    ONLY_DURING_COMBAT,
    OPPONENT_CONTROLS_FLYING_CREATURE,
    OPPONENT_CONTROLS_MORE_LANDS,
    ONLY_DURING_YOUR_TURN,
    ONLY_DURING_YOUR_UPKEEP,
    ONLY_DURING_ANY_UPKEEP,
    ONLY_WHILE_ATTACKING,
    ONLY_WHILE_CREATURE,
    POWER_4_OR_GREATER,
    RAID,
    SORCERY_SPEED
}
