package com.github.laxika.magicalvibes.model;

public enum AwaitingInput {

    ATTACKER_DECLARATION,
    BLOCKER_DECLARATION,
    CARD_CHOICE,
    TARGETED_CARD_CHOICE,
    PERMANENT_CHOICE,
    GRAVEYARD_CHOICE,
    COLOR_CHOICE,
    MAY_ABILITY_CHOICE,
    MULTI_PERMANENT_CHOICE,
    LIBRARY_REORDER,
    DISCARD_CHOICE
}
