package com.github.laxika.magicalvibes.model;

public enum AwaitingInput {

    ATTACKER_DECLARATION,
    BLOCKER_DECLARATION,
    CARD_CHOICE,
    TARGETED_CARD_CHOICE,
    PERMANENT_CHOICE,
    GRAVEYARD_CHOICE,
    COLOR_CHOICE,
    MAY_ABILITY_CHOICE,
    MULTI_PERMANENT_CHOICE,
    MULTI_GRAVEYARD_CHOICE,
    LIBRARY_REORDER,
    LIBRARY_SEARCH,
    DISCARD_CHOICE,
    ACTIVATED_ABILITY_DISCARD_COST_CHOICE,
    REVEALED_HAND_CHOICE,
    HAND_TOP_BOTTOM_CHOICE,
    LIBRARY_REVEAL_CHOICE
}
