package com.github.laxika.magicalvibes.model;

public enum CounterType {
    AGE,
    AIM,
    ANY,
    ARROW,
    ARROWHEAD,
    AWAKENING,
    BAIT,
    BLAZE,
    BLOOD,
    BOUNTY,
    BRIBERY,
    BOOK,
    BRICK,
    CARRION,
    CHARGE,
    CORPSE,
    CUBE,
    CREDIT,
    CURRENCY,
    DEATH,
    DEVOTION,
    DELAY,
    DESPAIR,
    DIVINITY,
    DOOM,
    ECHO,
    EMBER,
    ELIXIR,
    EON,
    EYEBALL,
    FADE,
    FATE,
    FEATHER,
    FILIBUSTER,
    FINALITY,
    FLAME,
    FLOOD,
    FUNGUS,
    FUSE,
    GEM,
    GHOSTFORM,
    GOLD,
    GROWTH,
    HEALING,
    HATCHLING,
    HOUR,
    HOURGLASS,
    HOOFPRINT,
    HUNGER,
    ICE,
    FELLOWSHIP,
    INCUBATION,
    INFECTION,
    INCARNATION,
    UNITY,
    INVITATION,
    JAVELIN,
    KI,
    LANDMARK,
    LEVEL,
    LOYALTY,
    LUCK,
    MAGNET,
    MANIFESTATION,
    MINE,
    NIGHT,
    DEFENSE,
    DEPLETION,
    MANNEQUIN,
    MINING,
    MUSIC,
    NET,
    MUSTER,
    MINUS_ONE_MINUS_ONE,
    MINUS_ONE_MINUS_ZERO,
    MINUS_TWO_MINUS_ONE,
    MINUS_TWO_MINUS_TWO,
    MINUS_ZERO_MINUS_ONE,
    MINUS_ZERO_MINUS_TWO,
    OMEN,
    OIL,
    ORE,
    PAIN,
    PARALYZATION,
    PETAL,
    PETRIFICATION,
    PHYLACTERY,
    PIN,
    POINT,
    POLYP,
    PLAGUE,
    PRESSURE,
    PREY,
    PUPA,
    QUEST,
    REVIVAL,
    RITUAL,
    RUST,
    PLUS_ONE_PLUS_ONE,
    PLUS_ONE_PLUS_ZERO,
    PLUS_ONE_PLUS_TWO,
    PLUS_TWO_PLUS_TWO,
    PLUS_ZERO_PLUS_ONE,
    PLUS_TWO_PLUS_ZERO,
    PLUS_ZERO_PLUS_TWO,
    SCREAM,
    SHELL,
    SLEIGHT,
    SLIME,
    SHRED,
    SOOT,
    SOUL,
    STORAGE,
    STUDY,
    STUN,
    THEFT,
    TIDE,
    WIND,
    WISH,
    LORE,
    LOOT,
    SILVER,
    PAGE,
    TOWER,
    TIME,
    TRAINING,
    TREASURE,
    VALOR,
    VELOCITY,
    VERSE,
    VITALITY,
    VORTEX,
    WAGE,
    DEATHTOUCH,
    DECAYED,
    FLYING,
    FIRST_STRIKE,
    HEXPROOF,
    INDESTRUCTIBLE,
    LIFELINK,
    REACH,
    TRAMPLE,
    WINCH;

    public Keyword grantedKeyword() {
        return switch (this) {
            case FLYING -> Keyword.FLYING;
            case FIRST_STRIKE -> Keyword.FIRST_STRIKE;
            case DEATHTOUCH -> Keyword.DEATHTOUCH;
            case DECAYED -> Keyword.DECAYED;
            case LIFELINK -> Keyword.LIFELINK;
            case HEXPROOF -> Keyword.HEXPROOF;
            case INDESTRUCTIBLE -> Keyword.INDESTRUCTIBLE;
            case REACH -> Keyword.REACH;
            case TRAMPLE -> Keyword.TRAMPLE;
            default -> null;
        };
    }
}
