package com.github.laxika.magicalvibes.model;

public enum EffectSlot {
    ON_TAP,
    ON_ENTER_BATTLEFIELD,
    SPELL,
    ON_ALLY_CREATURE_ENTERS_BATTLEFIELD,
    ON_ANY_OTHER_CREATURE_ENTERS_BATTLEFIELD,
    STATIC,
    ON_SACRIFICE,
    ON_BLOCK,
    UPKEEP_TRIGGERED,
    EACH_UPKEEP_TRIGGERED,
    OPPONENT_UPKEEP_TRIGGERED,
    ON_ANY_PLAYER_CASTS_SPELL,
    ON_DEATH,
    ON_ALLY_CREATURE_DIES,
    ON_COMBAT_DAMAGE_TO_PLAYER,
    ON_DAMAGE_TO_PLAYER,
    ON_ATTACK,
    ON_BECOMES_BLOCKED,
    EACH_DRAW_TRIGGERED,
    ON_OPPONENT_DISCARDS,
    ON_SELF_DISCARDED_BY_OPPONENT,
    ON_ANY_PLAYER_TAPS_LAND
}
