package com.github.laxika.magicalvibes.model;

public enum EffectSlot {
    ON_TAP,
    ON_ENTER_BATTLEFIELD,
    SPELL,
    ON_ALLY_CREATURE_ENTERS_BATTLEFIELD,
    ON_ANY_OTHER_CREATURE_ENTERS_BATTLEFIELD,
    STATIC,
    ON_SACRIFICE,
    ON_BLOCK,
    UPKEEP_TRIGGERED,
    ON_ANY_PLAYER_CASTS_SPELL
}
