package com.github.laxika.magicalvibes.model;

import java.util.Map;

public enum Keyword {

    FLYING,
    REACH,
    DEFENDER,
    DOUBLE_STRIKE,
    FIRST_STRIKE,
    FLASH,
    SPLIT_SECOND,
    FADING,
    VANISHING,
    VIGILANCE,
    BACKUP,
    SHROUD,
    CHANGELING,
    FEAR,
    MENACE,
    INDESTRUCTIBLE,
    CONVOKE,
    IMPROVISE,
    HARMONIZE,
    HASTE,
    RIOT,
    TRAMPLE,
    LIFELINK,
    FORESTWALK,
    MOUNTAINWALK,
    ISLANDWALK,
    SWAMPWALK,
    PLAINSWALK,
    HEXPROOF,
    INFECT,
    WITHER,
    INTIMIDATE,
    METALCRAFT,
    BATTLE_CRY,
    LIVING_WEAPON,
    DEATHTOUCH,
    SCRY,
    FLASHBACK,
    AFTERMATH,
    TRANSFORM,
    DAYBOUND,
    NIGHTBOUND,
    KICKER,
    BARGAIN,
    CREW,
    EXPLORE,
    EXPLOIT,
    UNDYING,
    PERSIST,
    CONVERGE,
    INCREMENT,
    PARADIGM,
    HORSEMANSHIP,
    SHADOW,
    FLANKING,
    CONSPIRE,
    RETRACE,
    JUMP_START,
    BANDING,
    EMERGE,
    COVEN,
    MELD,
    TRAINING,
    DISTURB,
    MORPH,
    SKULK,
    SOULBOND,
    MIRACLE,
    MADNESS,
    ESCALATE,
    DECAYED,
    AFTERLIFE,
    BLIGHT,
    SPLICE,
    DELIRIUM,
    PREPARED,
    PHASING,
    BUYBACK,
    EVOLVE,
    ADAPT,
    FUSE,
    OFFERING,
    DELVE,
    DREDGE,
    MODULAR,
    SUNBURST,
    PROTOTYPE,
    REBOUND,
    RECOVER,
    START_YOUR_ENGINES,
    MAX_SPEED,
    EPIC,
    TOXIC,
    COMPLEATED,
    MOBILIZE,
    WEB_SLINGING,
    MAYHEM,
    SUSPECT,
    CAMOUFLAGE,
    DOUBLE,
    PLOT,
    AMASS;

    /**
     * Maps each landwalk keyword to the land subtype it walks over.
     */
    public static final Map<Keyword, CardSubtype> LANDWALK_MAP = Map.of(
            FORESTWALK, CardSubtype.FOREST,
            MOUNTAINWALK, CardSubtype.MOUNTAIN,
            ISLANDWALK, CardSubtype.ISLAND,
            SWAMPWALK, CardSubtype.SWAMP,
            PLAINSWALK, CardSubtype.PLAINS
    );
}
