package com.github.laxika.magicalvibes.model;

public enum LibrarySearchDestination {
    HAND,
    BATTLEFIELD,
    BATTLEFIELD_TAPPED,
    EXILE_IMPRINT,
    EXILE,
    EXILE_PLAYABLE,
    TOP_OF_LIBRARY,
    GRAVEYARD,
    BATTLEFIELD_ATTACHED_TO_PLAYER,
    BATTLEFIELD_ATTACHED_TO_CREATURE,
    SPHINX_AMBASSADOR,
    CAST_WITHOUT_PAYING
}
