# Examples:
#   .\scripts\run-fuzz-and-fix.ps1
#   .\scripts\run-fuzz-and-fix.ps1 -Rounds 500 -Model gpt-5.6-luna -Effort xhigh

param(
    # Number of random AI games to run. The repository default for this script is 500.
    [ValidateRange(1, 1000000)]
    [int] $Rounds = 500,

    # Codex model used to diagnose and fix a failed fuzz run.
    [string] $Model = "gpt-5.6-luna",

    # Reasoning effort used by the Codex repair instance.
    [ValidateSet("low", "medium", "high", "xhigh", "max")]
    [string] $Effort = "max"
)

$ErrorActionPreference = "Stop"

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$gradleWrapper = Join-Path $repositoryRoot "gradlew.bat"
$logPath = Join-Path $repositoryRoot "fuzz.log"
$testClass = "com.github.laxika.magicalvibes.ai.RandomAiFuzzTest"

if (-not (Test-Path -LiteralPath $gradleWrapper)) {
    Write-Error "Gradle wrapper not found at $gradleWrapper."
    exit 1
}

if (-not (Get-Command codex -ErrorAction SilentlyContinue)) {
    Write-Error "The 'codex' CLI was not found on PATH."
    exit 1
}

Write-Host "Running $Rounds Random AI fuzz games. Full output: $logPath"

Push-Location $repositoryRoot
try {
    $gradleCommand = ".\gradlew.bat :magical-vibes-ai:test --tests `"$testClass`" -DrunCardFuzz=true -DfuzzGames=$Rounds -Dorg.gradle.jvmargs=`"-Xmx6g`" --info --rerun --console=plain > `"$logPath`" 2>&1"
    & cmd /d /s /c $gradleCommand
    $gradleExitCode = $LASTEXITCODE
}
finally {
    Pop-Location
}

if (-not (Test-Path -LiteralPath $logPath)) {
    Write-Error "The fuzz command produced no log at $logPath."
    exit 1
}

$successMarker = "All $Rounds fuzz games passed."
$logShowsSuccess = [bool](Select-String -LiteralPath $logPath -SimpleMatch $successMarker -Quiet)
$logShowsFailure = [bool](Select-String -LiteralPath $logPath -Pattern '^FAILURE:|^BUILD FAILED|^RandomAiFuzzTest > .* FAILED$|^> Task :magical-vibes-ai:test FAILED$' -Quiet)

if ($gradleExitCode -eq 0 -and $logShowsSuccess -and -not $logShowsFailure) {
    Write-Host "PASS: all $Rounds fuzz games completed successfully."
    exit 0
}

Write-Warning "The fuzz run failed or did not reach its success marker (Gradle exit code $gradleExitCode)."
Write-Host "Relevant log lines:"
Select-String -LiteralPath $logPath -Pattern '^FAILURE:|^BUILD FAILED|^RandomAiFuzzTest > .* FAILED$|^> Task :magical-vibes-ai:test FAILED$|^All [0-9]+ fuzz games passed\.$' |
    Select-Object -Last 20 |
    ForEach-Object { Write-Host "  $($_.Line)" }
Write-Host "Starting a fresh Codex repair instance (model: $Model, effort: $Effort)..."

$prompt = @"
The RandomAiFuzzTest run for $Rounds games failed with Gradle exit code $gradleExitCode.

Inspect the complete fuzz log at fuzz.log and any test results generated by this run under magical-vibes-ai/build/test-results/test (verify result timestamps before relying on them). Diagnose the root cause and implement a rules-correct fix. Follow AGENTS.md, preserve unrelated working-tree changes, and do not commit. Add focused behavioral regression tests where practical. If the fix changes AiDecisionEngine.java, always add or update focused integration coverage in EasyAiDecisionEngineTest, MediumAiDecisionEngineTest, and HardAiDecisionEngineTest; do not rely only on AiDecisionEngineTest. Do not run the full test suite or rerun the 500-game fuzz test; run only focused tests relevant to the fix. If Magic rules are ambiguous, verify the official ruling before changing behavior. Do not ask clarifying questions or stop at a diagnosis: make the best fix you can and verify it.
"@

$reasoningConfig = "model_reasoning_effort=`"$Effort`""
& {
    # A non-Stop preference prevents native stderr from becoming terminating
    # NativeCommandError records under Windows PowerShell 5.1.
    $ErrorActionPreference = "Ignore"
    & codex --search --ask-for-approval never exec --model $Model --config $reasoningConfig --cd $repositoryRoot $prompt
}
$codexExitCode = $LASTEXITCODE

if ($codexExitCode -ne 0) {
    Write-Error "Codex exited with code $codexExitCode while attempting the fuzz fix."
    exit $codexExitCode
}

Write-Host "Codex finished its repair attempt. The failing fuzz log remains at $logPath."
exit 0
