package com.github.laxika.magicalvibes.model;

public enum MessageType {
    LOGIN,
    CREATE_GAME,
    JOIN_GAME,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    TIMEOUT,
    GAME_JOINED,
    OPPONENT_JOINED,
    NEW_GAME,
    GAME_UPDATED,
    PASS_PRIORITY,
    PRIORITY_UPDATED,
    STEP_ADVANCED,
    TURN_CHANGED,
    GAME_LOG_ENTRY,
    KEEP_HAND,
    TAKE_MULLIGAN,
    HAND_DRAWN,
    MULLIGAN_RESOLVED,
    GAME_STARTED,
    SELECT_CARDS_TO_BOTTOM,
    BOTTOM_CARDS,
    ERROR
}
